package jp.takukairo.gamesystem;
import org.springframework.stereotype.Service;
import org.springframework.core.io.ClassPathResource;
import jp.takukairo.common.*;
import static jp.takukairo.common.Json.*;
import java.util.*;
import java.text.Normalizer;
@Service
public class Profiles {
 private final List<Map<String,Object>> definitions;private final Map<String,Object> resolver;
 public Profiles(){try{definitions=Json.MAPPER.readValue(new ClassPathResource("config/profiles.json").getInputStream(),new com.fasterxml.jackson.core.type.TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}try{resolver=Json.MAPPER.readValue(new ClassPathResource("config/resolver.json").getInputStream(),new com.fasterxml.jackson.core.type.TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}
 public static String normalize(String v){return v==null?"":Normalizer.normalize(v.replaceAll("^[\\p{Z}\\s\\uFEFF]+|[\\p{Z}\\s\\uFEFF]+$",""),Normalizer.Form.NFKC);}
 public List<Map<String,Object>> active(){return definitions.stream().filter(p->Boolean.TRUE.equals(p.get("active"))).map(p->map("profileKey",p.get("profileKey"),"canonicalSystemKey",p.get("canonicalSystemKey"),"displayName",p.get("displayName"),"configRevision",p.get("configRevision"))).toList();}
 public Map<String,Object> get(String key){return definitions.stream().filter(p->p.get("profileKey").equals(key)).findFirst().orElseThrow(ApiException::notFound);}
 public Map<String,Object> resolveProfile(String input){String name=normalize(input);return list(resolver.get("exactEntries")).stream().filter(e->normalize(text(e.get("input"))).equals(name)).map(e->activeCanonical(text(e.get("canonicalSystemKey")))).filter(Objects::nonNull).findFirst().orElse(null);}
 public Map<String,Object> resolve(String input){var p=resolveProfile(input);var candidates=new ArrayList<Object>();if(p==null){for(var alias:list(resolver.get("aliases")))if(normalize(text(alias.get("input"))).equals(normalize(input)))for(Object key:(List<?>)alias.get("canonicalSystemKeys")){var active=activeCanonical(text(key));if(active!=null)candidates.add(map("canonicalSystemKey",active.get("canonicalSystemKey"),"profileKey",active.get("profileKey"),"displayName",active.get("displayName")));}}return map("state",p!=null?"EXACT":candidates.isEmpty()?"UNKNOWN":"SUGGESTED","input",input,"canonicalSystemKey",p==null?null:p.get("canonicalSystemKey"),"profileKey",p==null?null:p.get("profileKey"),"displayName",p==null?null:p.get("displayName"),"candidates",candidates);}
 public Map<String,Object> activeCanonical(String canonical){return definitions.stream().filter(p->Boolean.TRUE.equals(p.get("active"))&&Objects.equals(p.get("canonicalSystemKey"),canonical)).findFirst().orElse(null);}
 public void validateValues(String key,Map<String,Object> values,String path,Map<String,Object> previous){if(key==null){if(!values.isEmpty())throw ApiException.invalid(path,"UNSUPPORTED_PROFILE","設定形式を確認してください。");return;}var p=get(key);validateFields(list(p.get("pcFields")),values,path,p,previous);}
 private void validateFields(List<Map<String,Object>> fields,Map<String,Object> values,String path,Map<String,Object> profile,Map<String,Object> previous){
  Set<String> allowed=new HashSet<>();for(var f:fields)allowed.add(text(f.get("key")));for(String k:values.keySet())if(!allowed.contains(k))throw ApiException.invalid(path+"/"+k,"UNKNOWN_FIELD","設定にない項目です。");
  for(var f:fields){String k=text(f.get("key")),type=text(f.get("inputType"));Object v=values.get(k);if(v==null){if(Boolean.TRUE.equals(f.get("required")))throw ApiException.invalid(path+"/"+k,"REQUIRED","入力してください。");continue;}boolean valid=switch(type){case "TEXT","SELECT"->v instanceof String;case "INTEGER"->v instanceof Integer||v instanceof Long;case "BOOLEAN"->v instanceof Boolean;case "REPEATER"->v instanceof List<?>;default->false;};if(!valid)throw ApiException.invalid(path+"/"+k,"INVALID_TYPE","値の形式を確認してください。");var validation=obj(f.get("validation"));
   if(type.equals("TEXT")&&validation.get("maxLength") instanceof Number n&&((String)v).codePointCount(0,((String)v).length())>n.intValue())throw ApiException.invalid(path+"/"+k,"TOO_LONG","入力が長すぎます。");
   if(type.equals("INTEGER")){long value=((Number)v).longValue();if(validation.get("min") instanceof Number n&&value<n.longValue()||validation.get("max") instanceof Number max&&value>max.longValue())throw ApiException.invalid(path+"/"+k,"OUT_OF_RANGE","値を確認してください。");}
   if(type.equals("SELECT")){var ref=obj(f.get("optionSourceRef"));var source=list(profile.get("optionSources")).stream().filter(o->Objects.equals(o.get("sourceKey"),ref.get("sourceKey"))).findFirst().orElseThrow();var option=list(source.get("options")).stream().filter(o->Objects.equals(o.get("key"),v)).findFirst().orElse(null);if(option==null||!Boolean.TRUE.equals(option.get("selectable"))&&!Objects.equals(previous.get(k),v))throw ApiException.invalid(path+"/"+k,"INVALID_OPTION","選択肢を確認してください。");}
   if(type.equals("REPEATER")){var rawItems=(List<?>)v;for(int i=0;i<rawItems.size();i++)if(!(rawItems.get(i) instanceof Map<?,?>))throw ApiException.invalid(path+"/"+k+"/"+i,"INVALID_TYPE","行の形式を確認してください。");var items=list(v);if(validation.get("minItems") instanceof Number n&&items.size()<n.intValue()||validation.get("maxItems") instanceof Number max&&items.size()>max.intValue())throw ApiException.invalid(path+"/"+k,"INVALID_COUNT","件数を確認してください。");for(int i=0;i<items.size();i++)validateFields(list(f.get("itemFields")),items.get(i),path+"/"+k+"/"+i,profile,previous.get(k) instanceof List<?> prior&&i<prior.size()?obj(prior.get(i)):Map.of());}
  }
 }
 public void validateState(String key,Map<String,Object> values,String path){if(key==null){if(!values.isEmpty())throw ApiException.invalid(path,"UNSUPPORTED_PROFILE","設定形式を確認してください。");return;}var p=get(key);Set<String> keys=new HashSet<>();for(var f:list(p.get("endStateStatuses")))keys.add(text(f.get("key")));for(var e:values.entrySet()){if(!keys.contains(e.getKey()))throw ApiException.invalid(path+"/"+e.getKey(),"UNKNOWN_FIELD","設定にない項目です。");if(e.getValue()!=null&&!(e.getValue() instanceof Integer||e.getValue() instanceof Long))throw ApiException.invalid(path+"/"+e.getKey(),"INVALID_INTEGER","整数を入力してください。");}}
}
