package jp.takukairo.scenario;
import jp.takukairo.common.*;
import jp.takukairo.security.*;
import jp.takukairo.model.*;
import jp.takukairo.gamesystem.*;
import static jp.takukairo.common.Json.*;
import static jp.takukairo.common.Validation.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.*;
@Service @Transactional
public class LibraryService {
 private final Store s;private final CurrentUser user;private final Profiles profiles;private final jp.takukairo.image.Cleanup cleanup;
 public LibraryService(Store s,CurrentUser u,Profiles p,jp.takukairo.image.Cleanup c){this.s=s;user=u;profiles=p;cleanup=c;}
 public Map<String,Object> personDto(Person p){return map("id",p.id,"version",p.version,"displayName",p.displayName);}
 public Map<String,Object> scenarioDto(Scenario p){return map("id",p.id,"version",p.version,"name",p.name,"authorName",p.authorName,"sourceUrl",p.sourceUrl,"gameSystem",p.gameSystem,"externalImageUrl",p.externalImageUrl,"image",p.imageDerivativeKey==null?null:map("present",true),"createdAt",p.createdAt,"updatedAt",p.updatedAt,"favorite",s.count("select count(e) from ScenarioFavorite e where e.userId=:u and e.scenarioId=:id","u",user.id(),"id",p.id)>0,"tableCount",s.count("select count(e) from TrpgTable e where e.scenarioId=:id","id",p.id));}
 public Map<String,Object> pcDto(Pc p){var settings=s.query(PcSystemSetting.class,"where e.pcId=:id order by e.displayOrder","id",p.id);return map("id",p.id,"version",p.version,"name",p.name,"personId",p.personId,"person",personDto(s.find(Person.class,p.personId)),"characterSheetUrl",p.characterSheetUrl,"image",p.imageDerivativeKey==null?null:map("present",true,"positionX",p.imagePositionX,"positionY",p.imagePositionY,"zoom",p.imageZoom),"createdAt",p.createdAt,"systemSettings",settings.stream().map(x->map("id",x.id,"gameSystemName",x.gameSystemName,"canonicalSystemKey",x.canonicalSystemKey,"profileKey",x.profileKey,"profileValues",object(x.profileValues),"characterSheetUrl",x.characterSheetUrl,"displayOrder",x.displayOrder)).toList());}
 public List<Map<String,Object>> scenarios(String search,List<String> roles,Boolean favorite,String sort){var data=s.query(Scenario.class,"where e.userId=:u","u",user.id());List<Scenario> found=new ArrayList<>();String term=search==null?"":search.toLowerCase(Locale.ROOT);for(var p:data){var dto=scenarioDto(p);if(favorite!=null&&!Objects.equals(favorite,dto.get("favorite")))continue;var tables=s.query(TrpgTable.class,"where e.scenarioId=:id","id",p.id);boolean roleMatch=roles==null||roles.isEmpty();StringBuilder names=new StringBuilder(p.name+" "+p.authorName);for(var t:tables){for(var x:s.query(Participation.class,"where e.tableId=:id","id",t.id)){if(Objects.equals(x.personId,user.user().selfPersonId)&&roles!=null&&roles.contains(x.role))roleMatch=true;names.append(' ').append(s.find(Person.class,x.personId).displayName);if(x.pcId!=null)names.append(' ').append(s.find(Pc.class,x.pcId).name);}}if(!roleMatch||!names.toString().toLowerCase(Locale.ROOT).contains(term))continue;found.add(p);}Comparator<Scenario> comparator=switch(sort==null?"RECENT_PLAYED":sort){case "NAME"->Comparator.comparing(x->x.name);case "CREATED_ASC"->Comparator.comparing(x->x.createdAt);case "CREATED_DESC"->Comparator.comparing((Scenario x)->x.createdAt).reversed();default->Comparator.comparing((Scenario x)->recentScenario(x.id),Comparator.nullsLast(Comparator.reverseOrder()));};found.sort(comparator.thenComparing(x->x.id));return found.stream().map(this::scenarioDto).toList();}
 private Instant recentScenario(Long id){return s.query(TrpgTable.class,"where e.scenarioId=:id","id",id).stream().map(this::basis).max(Comparator.naturalOrder()).orElse(Instant.MIN);}
 public Instant basis(TrpgTable t){return s.query(TableDate.class,"where e.tableId=:id order by e.playedOn desc","id",t.id).stream().findFirst().map(d->d.playedOn.atStartOfDay(ZoneOffset.UTC).toInstant()).orElse(t.createdAt);}
 public Object scenario(long id){return scenarioDto(user.owned(Scenario.class,id));}
 public Object saveScenario(Long id,Map<String,Object> b){Scenario p=id==null?new Scenario():user.owned(Scenario.class,id);if(id!=null)Store.version(p.version,requiredLong(b,"version"));else p.userId=user.id();if(b.containsKey("name")||id==null)p.name=name(b.get("name"),"/name");if(b.containsKey("authorName"))p.authorName=optional(b.get("authorName"));if(b.containsKey("gameSystem"))p.gameSystem=optional(b.get("gameSystem"));if(b.containsKey("sourceUrl"))p.sourceUrl=url(b.get("sourceUrl"),"/sourceUrl");if(b.containsKey("externalImageUrl")){String ext=url(b.get("externalImageUrl"),"/externalImageUrl");if(ext!=null){var u=s.lock(AppUser.class,user.id());if(u.externalImageConsentAt==null){if(!Boolean.TRUE.equals(b.get("externalImageConsentAccepted")))throw ApiException.invalid("/externalImageConsentAccepted","CONSENT_REQUIRED","外部画像の利用説明を確認してください。");u.externalImageConsentAt=Instant.now();}}p.externalImageUrl=ext;}p.updatedAt=Instant.now();if(id==null)s.save(p);s.flush();return scenarioDto(p);}
 public void deleteScenario(long id){var p=user.owned(Scenario.class,id);if(s.count("select count(e) from TrpgTable e where e.scenarioId=:id","id",id)>0)throw new ApiException(409,"CONFLICT","関連する卓があるため削除できません。");cleanup.schedule(p.imageMasterKey);cleanup.schedule(p.imageDerivativeKey);for(var f:s.query(ScenarioFavorite.class,"where e.scenarioId=:id","id",id))s.remove(f);s.remove(p);}
 public void favorite(long id,boolean enabled){user.owned(Scenario.class,id);var u=s.lock(AppUser.class,user.id());var all=s.query(ScenarioFavorite.class,"where e.userId=:u and e.scenarioId=:id","u",u.id,"id",id);if(enabled&&all.isEmpty()){var f=new ScenarioFavorite();f.userId=u.id;f.scenarioId=id;s.save(f);}if(!enabled)all.forEach(s::remove);}
 public Object duplicate(Map<String,Object> b){String name=optional(b.get("name")),author=optional(b.get("authorName")),url=url(b.get("sourceUrl"),"/sourceUrl");return s.query(Scenario.class,"where e.userId=:u","u",user.id()).stream().filter(p->url!=null&&url.equals(p.sourceUrl)||Objects.equals(name,p.name)&&Objects.equals(author,p.authorName)).map(this::scenarioDto).toList();}
 public List<Map<String,Object>> persons(String search,boolean recent){String term=search==null?"":search.toLowerCase(Locale.ROOT);var all=s.query(Person.class,"where e.userId=:u","u",user.id()).stream().filter(p->p.displayName.toLowerCase(Locale.ROOT).contains(term)).toList();if(recent)all=all.stream().sorted(Comparator.comparing((Person p)->recentPerson(p.id),Comparator.reverseOrder())).limit(5).toList();return all.stream().map(this::personDto).toList();}
 private Instant recentPerson(Long id){return s.query(Participation.class,"where e.personId=:id","id",id).stream().map(p->basis(s.find(TrpgTable.class,p.tableId))).max(Comparator.naturalOrder()).orElse(Instant.MIN);}
 public Object savePerson(Long id,Map<String,Object>b){Person p=id==null?new Person():user.owned(Person.class,id);if(id==null)p.userId=user.id();else Store.version(p.version,requiredLong(b,"version"));p.displayName=name(b.get("displayName"),"/displayName");p.updatedAt=Instant.now();if(id==null)s.save(p);s.flush();return personDto(p);}
 public Object impact(long id){user.owned(Person.class,id);return map("relatedPcCount",s.count("select count(e) from Pc e where e.personId=:id","id",id),"relatedTableCount",s.count("select count(distinct e.tableId) from Participation e where e.personId=:id","id",id));}
 public void deletePerson(long id){var p=user.owned(Person.class,id);if(Objects.equals(user.user().selfPersonId,id)||s.count("select count(e) from Pc e where e.personId=:id","id",id)>0||s.count("select count(e) from Participation e where e.personId=:id","id",id)>0)throw new ApiException(409,"CONFLICT","参照されている人物は削除できません。");s.remove(p);}
 public Object pc(long id){return pcDto(user.owned(Pc.class,id));}
 public List<Map<String,Object>> pcs(String search,Long personId,String sort){String term=search==null?"":search.toLowerCase(Locale.ROOT);var all=s.query(Pc.class,"where e.userId=:u","u",user.id()).stream().filter(p->personId==null||p.personId.equals(personId)).filter(p->(p.name+" "+s.find(Person.class,p.personId).displayName).toLowerCase(Locale.ROOT).contains(term));Comparator<Pc> comparator=switch(sort==null?"CREATED_DESC":sort){case "NAME"->Comparator.comparing(p->p.name);case "CREATED_ASC"->Comparator.comparing(p->p.createdAt);case "RECENT"->Comparator.comparing((Pc p)->recentPc(p.id),Comparator.reverseOrder());default->Comparator.comparing((Pc p)->p.createdAt).reversed();};return all.sorted(comparator.thenComparing(p->p.id)).map(this::pcDto).toList();}
 private Instant recentPc(Long id){return s.query(Participation.class,"where e.pcId=:id","id",id).stream().map(p->basis(s.find(TrpgTable.class,p.tableId))).max(Comparator.naturalOrder()).orElse(Instant.MIN);}
 public Object savePc(Long id,Map<String,Object>b){Pc p=id==null?new Pc():user.owned(Pc.class,id);if(id==null){p.userId=user.id();p.personId=requiredLong(b,"personId");user.owned(Person.class,p.personId);}else{Store.version(p.version,requiredLong(b,"version"));if(b.containsKey("personId")&&!p.personId.equals(Json.id(b.get("personId"))))throw ApiException.invalid("/personId","USE_CHANGE_PERSON","PL変更操作を使用してください。");}if(id==null||b.containsKey("name"))p.name=name(b.get("name"),"/name");if(b.containsKey("characterSheetUrl"))p.characterSheetUrl=url(b.get("characterSheetUrl"),"/characterSheetUrl");if(id==null){s.save(p);s.flush();}
  if(b.containsKey("systemSettings")){var old=s.query(PcSystemSetting.class,"where e.pcId=:id","id",p.id);Set<Long> keep=new HashSet<>();Set<String> canonicals=new HashSet<>();int i=0;for(var x:list(b.get("systemSettings"))){String path="/systemSettings/"+i;Long sid=Json.id(x.get("id"));var v=sid==null?new PcSystemSetting():s.find(PcSystemSetting.class,sid);if(sid!=null&&!v.pcId.equals(p.id))throw ApiException.notFound();String canonical=optional(x.get("canonicalSystemKey")),key=optional(x.get("profileKey"));if(canonical!=null&&!canonicals.add(canonical))throw ApiException.invalid(path+"/canonicalSystemKey","DUPLICATE","同じゲームシステムは複数設定できません。");if(sid!=null&&Objects.equals(v.canonicalSystemKey,canonical)&&!Objects.equals(v.profileKey,key)){var active=profiles.activeCanonical(canonical);if(active==null||!Objects.equals(active.get("profileKey"),key))throw ApiException.invalid(path+"/profileKey","PROFILE_MIGRATION_NOT_AVAILABLE","現在、このゲームシステムの設定形式は更新できません。");}if(key!=null){var def=profiles.get(key);if(!Objects.equals(def.get("canonicalSystemKey"),canonical))throw ApiException.invalid(path+"/profileKey","PROFILE_MISMATCH","設定形式を確認してください。");if((sid==null||!Objects.equals(v.profileKey,key))&&!Boolean.TRUE.equals(def.get("active")))throw ApiException.invalid(path+"/profileKey","PROFILE_MIGRATION_NOT_AVAILABLE","現在の設定形式を選択してください。");}profiles.validateValues(key,obj(x.get("profileValues")),path+"/profileValues",sid==null?Map.of():object(v.profileValues));v.pcId=p.id;v.gameSystemName=name(x.get("gameSystemName"),path+"/gameSystemName");v.canonicalSystemKey=canonical;v.profileKey=key;v.profileValues=write(obj(x.get("profileValues")));v.characterSheetUrl=url(x.get("characterSheetUrl"),path+"/characterSheetUrl");v.displayOrder=++i;v.updatedAt=Instant.now();if(sid==null)s.save(v);else keep.add(sid);}old.stream().filter(x->!keep.contains(x.id)).forEach(s::remove);}
  p.updatedAt=Instant.now();s.flush();return pcDto(p);
 }
 public void deletePc(long id){var p=user.owned(Pc.class,id);if(s.count("select count(e) from Participation e where e.pcId=:id","id",id)>0)throw new ApiException(409,"CONFLICT","関連する卓があるため削除できません。");s.query(PcSystemSetting.class,"where e.pcId=:id","id",id).forEach(s::remove);cleanup.schedule(p.imageMasterKey);cleanup.schedule(p.imageDerivativeKey);s.remove(p);}
 public Object changeContext(long id){var p=user.owned(Pc.class,id);return map("pc",pcDto(p),"participations",s.query(Participation.class,"where e.pcId=:id order by e.tableId,e.id","id",id).stream().map(x->{var t=s.find(TrpgTable.class,x.tableId);return map("participationId",x.id,"participationVersion",x.version,"tableId",t.id,"tableVersion",t.version,"person",personDto(s.find(Person.class,x.personId)),"scenario",scenarioDto(s.find(Scenario.class,t.scenarioId)),"tableName",t.tableName);}).toList());}
 public Object changePerson(long id,Map<String,Object>b){var p=user.owned(Pc.class,id);Store.version(p.version,requiredLong(b,"pcVersion"));long newId=requiredLong(b,"newPersonId");user.owned(Person.class,newId);var updates=list(b.get("participationUpdates"));Set<Long> parents=new TreeSet<>();for(var x:updates){var part=s.find(Participation.class,requiredLong(x,"participationId"));if(!Objects.equals(part.pcId,id)||!Objects.equals(part.tableId,Json.id(x.get("tableId"))))throw ApiException.notFound();user.owned(TrpgTable.class,part.tableId);parents.add(part.tableId);}for(long tid:parents)s.lock(TrpgTable.class,tid);for(var x:updates){var part=s.find(Participation.class,requiredLong(x,"participationId"));Store.version(part.version,requiredLong(x,"participationVersion"));Store.version(s.find(TrpgTable.class,part.tableId).version,requiredLong(x,"tableVersion"));}for(var x:updates){var part=s.find(Participation.class,requiredLong(x,"participationId"));part.personId=newId;part.updatedAt=Instant.now();}for(long tid:parents)s.find(TrpgTable.class,tid).updatedAt=Instant.now();p.personId=newId;p.updatedAt=Instant.now();s.flush();return pcDto(p);}
}
