import {useState,useRef,useEffect,useId,useContext,createContext,type ReactNode} from 'react';
import {useBlocker} from 'react-router-dom';
import {createPortal} from 'react-dom';
import {ApiError} from '../api/client';
import type {FieldError} from '../api/types';
const logoutGuards=new Set<()=>Promise<boolean>>();
export function registerLogoutGuard(guard:()=>Promise<boolean>){logoutGuards.add(guard);return()=>{logoutGuards.delete(guard)}}
export async function canLogout(){for(const guard of logoutGuards)if(!await guard())return false;return true}
export const ConfirmContext=createContext<(text:string)=>Promise<boolean>>(async()=>false);
export function Dialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null),id=useId();useEffect(()=>{const trigger=document.activeElement as HTMLElement|null;const d=ref.current!;d.showModal();const control=d.querySelector<HTMLElement>('[autofocus],input,textarea,select,button');control?.focus();return()=>{d.close();trigger?.focus()}},[]);return createPortal(<dialog ref={ref} aria-labelledby={id} onKeyDown={e=>{if(e.key!=='Tab')return;const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('a[href],button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]')).filter(el=>el.getClientRects().length&&!el.closest('[hidden],[inert]'));const first=controls[0],last=controls.at(-1);if(!first){e.preventDefault();e.currentTarget.focus()}else if(e.shiftKey&&(document.activeElement===first||document.activeElement===e.currentTarget)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}} onCancel={e=>{e.preventDefault();onClose()}}><div className="dialog-heading"><h2 id={id}>{title}</h2><button className="quiet" aria-label="閉じる" onClick={onClose}>×</button></div>{children}</dialog>,document.body)}
export function ConfirmProvider({children}:{children:ReactNode}){const [pending,setPending]=useState<{text:string;resolve:(v:boolean)=>void}|null>(null);const confirm=(text:string)=>new Promise<boolean>(resolve=>setPending({text,resolve}));function finish(v:boolean){pending?.resolve(v);setPending(null)}return <ConfirmContext.Provider value={confirm}>{children}{pending&&<Dialog title="確認" onClose={()=>finish(false)}><p>{pending.text}</p><div className="dialog-actions"><button onClick={()=>finish(false)}>キャンセル</button><button className="primary" onClick={()=>finish(true)}>続ける</button></div></Dialog>}</ConfirmContext.Provider>}
export function useDirty(dirty:boolean){const confirm=useContext(ConfirmContext);const dirtyRef=useRef(dirty);dirtyRef.current=dirty;const blocker=useBlocker(()=>dirtyRef.current);useEffect(()=>registerLogoutGuard(async()=>{if(!dirtyRef.current)return true;const ok=await confirm('保存していない変更があります。ログアウトすると入力を破棄します。ログアウトしますか？');if(ok)dirtyRef.current=false;return ok}),[]);useEffect(()=>{if(blocker.state==='blocked'){let active=true;confirm('保存していない変更があります。画面を離れますか？').then(v=>{if(active){if(v)blocker.proceed();else blocker.reset()}});return()=>{active=false}}},[blocker.state]);useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[dirty]);return()=>{dirtyRef.current=false}}
export function focusPath(path:string){let el=document.querySelector<HTMLElement>(`[data-field-path="${CSS.escape(path)}"]`);if(!el){el=document.querySelector<HTMLElement>('[data-error-fallback]')}if(el){const tab=el.closest<HTMLElement>('[data-panel-key]')?.dataset.panelKey;if(tab)window.dispatchEvent(new CustomEvent('activate-error-tab',{detail:tab}));requestAnimationFrame(()=>{el!.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});el!.focus()})}}
export function useErrors(){const [error,setError]=useState<ApiError|null>(null);const report=(e:unknown)=>{const err=e instanceof ApiError?e:new ApiError(0,{code:'UNEXPECTED_ERROR',message:e instanceof Error?e.message:'処理を完了できませんでした。',fieldErrors:[]});setError(err);requestAnimationFrame(()=>{if(err.body.fieldErrors.length>=2)document.querySelector<HTMLElement>('[data-error-summary]')?.focus();else if(err.body.fieldErrors.length===1)focusPath(err.body.fieldErrors[0].path)})};return {error,report,clear:()=>setError(null)}}
export function ErrorPanel({error}:{error:ApiError|null}){if(!error)return null;const fields=error.body.fieldErrors;const unlinked=fields.length===1&&!document.querySelector('[data-field-path="'+CSS.escape(fields[0].path)+'"]');return <div>{fields.length>=2?<div className="error-summary" role="alert" tabIndex={-1} data-error-summary><h2>入力内容を確認してください</h2>{fields.map((e,i)=><button key={i} onClick={()=>focusPath(e.path)}>{e.message}</button>)}</div>:fields.length===0?<p className="notice" role="alert">{error.message}{error.body.code==='IMPORT_PREVIEW_STALE'&&' 確認結果が古くなりました。最新の内容で再確認してください。'}{error.body.code.includes('CONFLICT')&&' 入力を保持しています。最新の内容を読み込み、確認してください。'}</p>:null}{unlinked&&<p className="inline-error" role="alert" tabIndex={-1} data-error-fallback>{fields[0].message}</p>}{error.body.traceId&&<small>確認コード: {error.body.traceId}</small>}</div>}
export function Field({label,path,error,children}:{label:string;path:string;error:ApiError|null;children:ReactNode}){const errors=error?.body.fieldErrors.filter(e=>e.path===path)??[];return <div className="field"><label htmlFor={fieldId(path)}>{label}</label>{children}{errors.map((e,i)=><p id={fieldId(path)+'-error'+i} className="inline-error" key={i}>{e.message}</p>)}</div>}
export function fieldId(path:string){return 'f-'+path.replace(/[^a-zA-Z0-9_-]/g,'-')}
export function fieldProps(path:string,error:ApiError|null){const errs=error?.body.fieldErrors.filter(e=>e.path===path)??[];return {id:fieldId(path),'data-field-path':path,'aria-invalid':errs.length?true:undefined,'aria-describedby':errs.length?errs.map((_,i)=>fieldId(path)+'-error'+i).join(' '):undefined}}
export function Tabs({tabs,active,onChange}:{tabs:{key:string;label:string;error?:boolean}[];active:string;onChange:(key:string)=>void}){function key(e:React.KeyboardEvent,i:number){let index=i;if(e.key==='ArrowRight')index=(i+1)%tabs.length;else if(e.key==='ArrowLeft')index=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=tabs.length-1;else return;e.preventDefault();onChange(tabs[index].key);document.getElementById('tab-'+tabs[index].key)?.focus()}return <div role="tablist" className="tabs">{tabs.map((t,i)=><button id={'tab-'+t.key} key={t.key} role="tab" aria-selected={active===t.key} aria-controls={'panel-'+t.key} tabIndex={active===t.key?0:-1} onClick={()=>onChange(t.key)} onKeyDown={e=>key(e,i)}>{t.label}{t.error&&<span className="tab-error"> ・<span className="sr-only">入力エラーあり</span></span>}</button>)}</div>}
export function ComboBox<T extends {id:number}>({label,path,value,items,render,onSelect,onCreate,error,onSearch}:{label:string;path:string;value:T|null;items:T[];render:(v:T)=>string;onSelect:(v:T|null)=>void;onCreate?:()=>void;error:ApiError|null;onSearch?:(v:string)=>void}){const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0);const id=useId();const filtered=items.filter(v=>render(v).toLowerCase().includes(query.toLowerCase()));useEffect(()=>setQuery(value?render(value):''),[value?.id]);function keys(e:React.KeyboardEvent){if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setActive(v=>Math.clamp(v+(e.key==='ArrowDown'?1:-1),0,Math.max(0,filtered.length-1)))}else if(e.key==='Enter'&&open){e.preventDefault();if(filtered[active]){onSelect(filtered[active]);setQuery(render(filtered[active]));setOpen(false)}}else if(e.key==='Escape'){setOpen(false)}else if(e.key==='Tab')setOpen(false)}return <Field label={label} path={path} error={error}><div className="combo"><input {...fieldProps(path,error)} role="combobox" aria-expanded={open} aria-controls={id} aria-autocomplete="list" aria-activedescendant={open&&filtered[active]?id+'-'+filtered[active].id:undefined} value={query} onFocus={()=>{setOpen(true);setQuery('');onSearch?.('')}} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0);onSearch?.(e.target.value)}} onKeyDown={keys}/>{open&&<div className="combo-list"><div id={id} role="listbox" aria-label={label}>{filtered.map((item,i)=><div key={item.id} id={id+'-'+item.id} role="option" aria-selected={i===active} onMouseDown={e=>e.preventDefault()} onClick={()=>{onSelect(item);setQuery(render(item));setOpen(false)}}>{render(item)}</div>)}{filtered.length===0&&<p>候補がありません</p>}</div>{onCreate&&<button type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>{setOpen(false);onCreate()}}>＋ 新しい人物を追加</button>}<button type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>{onSelect(null);setQuery('');setOpen(false)}}>選択を解除</button></div>}</div></Field>}
export function ExternalLink({href,children}:{href:string|null|undefined;children:ReactNode}){if(!href||!/^https?:\/\//.test(href))return null;return <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>}
export function ExpandText({label,text}:{label:string;text:string|null|undefined}){const [expanded,setExpanded]=useState(false);if(!text)return null;const long=text.length>90||text.split('\n').length>3;return <div className="expand-text"><small>{label}</small><p>{long&&!expanded?text.slice(0,90)+'…':text}</p>{long&&<button className="quiet" onClick={()=>setExpanded(v=>!v)}>{expanded?'折りたたむ':'全文を見る'}</button>}</div>}
export function DateList({dates,parts=false}:{dates:{playedOn:string}[];parts?:boolean}){return <span>{[...dates].sort((a,b)=>a.playedOn.localeCompare(b.playedOn)).map((d,i)=><span key={i}>{i>0&&' / '}{parts&&dates.length>1&&<span className="part-label">PART {i+1}</span>}{d.playedOn.replaceAll('-','.')}</span>)}</span>}
declare global {interface Math {clamp(value:number,min:number,max:number):number}}
Math.clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
