package jp.takukairo;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.*;
import java.net.*;
import java.net.http.*;
import java.util.*;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.*;
import static org.junit.jupiter.api.Assertions.*;
import static jp.takukairo.common.Json.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test") @Testcontainers
class ContractIntegrationTest {
 @Container static final PostgreSQLContainer db=new PostgreSQLContainer("postgres:18.6");
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",db::getJdbcUrl);r.add("spring.datasource.username",db::getUsername);r.add("spring.datasource.password",db::getPassword);r.add("app.storage",()->"../.runtime/test-storage");}
 @LocalServerPort int port;@Autowired JdbcTemplate jdbc;HttpClient client;CookieManager cookies;String token;
 record Result(int status,Map<String,Object> body,String raw,HttpResponse<String> response){}
 @BeforeEach void setup()throws Exception{jdbc.execute("TRUNCATE app_user CASCADE");jdbc.execute("TRUNCATE storage_delete_task RESTART IDENTITY");jdbc.execute("TRUNCATE spring_session CASCADE");for(String table:List.of("app_user","person","scenario","pc","trpg_table","table_date","participation","end_pc_state","pc_system_setting","scenario_favorite","import_session","import_source","import_candidate","import_resolution","import_candidate_source_trace","storage_delete_task","import_preview"))jdbc.execute("ALTER SEQUENCE "+table+"_id_seq RESTART WITH 1");new ResourceDatabasePopulator(new ClassPathResource("db/dev/V1000__local_test_fixtures.sql")).execute(Objects.requireNonNull(jdbc.getDataSource()));cookies=new CookieManager(null,CookiePolicy.ACCEPT_ALL);client=HttpClient.newBuilder().cookieHandler(cookies).build();csrf();Result login=request("POST","/dev/session",null,true);assertEquals(200,login.status,login.raw);csrf();}
 void csrf()throws Exception{token=text(request("GET","/csrf",null,false).body.get("token"));}
 Result request(String method,String path,Object body,boolean csrf)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api"+path));if(csrf)b.header("X-CSRF-TOKEN",token);if(body!=null)b.header("Content-Type","application/json");b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(write(body)));var res=client.send(b.build(),HttpResponse.BodyHandlers.ofString());Map<String,Object> json;try{json=object(res.body());}catch(Exception e){json=map();}return new Result(res.statusCode(),json,res.body(),res);}
 Result get(String path)throws Exception{return request("GET",path,null,false);}Result post(String path,Object b)throws Exception{return request("POST",path,b,true);}Result patch(String path,Object b)throws Exception{return request("PATCH",path,b,true);}
 long number(Object v){return ((Number)v).longValue();}Map<String,Object> table(long id)throws Exception{return get("/tables/"+id).body;}
 void code(Result r,int status,String code){assertEquals(status,r.status,r.raw);assertEquals(code,r.body.get("code"),r.raw);assertTrue(r.body.containsKey("fieldErrors"));}
 Map<String,Object> draft(String name){return map("scenarioName",name,"gameSystemName",null,"tableName",null,"recordingUrl",null,"tableDates",List.of(),"participations",List.of(),"unassignedValues",List.of());}
 Map<String,Object> session()throws Exception{return post("/import/session",null).body;}long version(long sid)throws Exception{return number(get("/import/session/"+sid).body.get("version"));}
 List<Map<String,Object>> analyze(long sid,String text)throws Exception{assertEquals(201,post("/import/session/"+sid+"/sources/text",map("expectedSessionVersion",version(sid),"text",text)).status);assertEquals(200,post("/import/session/"+sid+"/analyze",map("expectedSessionVersion",version(sid))).status);return list(get("/import/session/"+sid+"/review?size=100").body.get("items"));}
 Map<String,Object> candidate(long sid,long cid)throws Exception{return obj(get("/import/session/"+sid+"/candidates/"+cid).body.get("candidate"));}
 Result candidatePatch(long sid,long cid,Map<String,Object>b)throws Exception{var body=new LinkedHashMap<>(b);body.put("expectedSessionVersion",version(sid));body.put("expectedVersion",candidate(sid,cid).get("version"));return patch("/import/session/"+sid+"/candidates/"+cid,body);}
 @Test void flywayAndHibernateValidateStarted(){assertEquals(3,jdbc.queryForObject("select count(*) from flyway_schema_history where success",Integer.class));assertTrue(jdbc.queryForObject("show server_version",String.class).startsWith("18.6"));}
 @Test void csrfRequiredAndFreshAfterLogin()throws Exception{code(request("POST","/persons",map("displayName","x"),false),403,"FORBIDDEN");assertEquals(201,post("/persons",map("displayName","x")).status);}
 @Test void cookieAndLogout()throws Exception{assertTrue(cookies.getCookieStore().getCookies().stream().anyMatch(c->c.getName().equals("TAKUKAIRO_SESSION_DEV")&&c.isHttpOnly()));assertEquals(204,post("/logout",null).status);assertEquals(false,get("/session").body.get("authenticated"));code(get("/scenarios"),401,"SESSION_EXPIRED");}
 @Test void setupGate()throws Exception{jdbc.execute("update app_user set self_person_id=null where id=1");code(get("/scenarios"),409,"SELF_PERSON_SETUP_REQUIRED");assertEquals(200,post("/self-person",map("displayName","new self")).status);}
 @Test void otherUserDenied()throws Exception{for(String p:List.of("/scenarios/11","/persons/13/impact","/pcs/15"))code(get(p),404,"NOT_FOUND");code(patch("/scenarios/11",map("version",0,"name","x")),404,"NOT_FOUND");}
 @Test void duplicateNamesAndDatesAllowed()throws Exception{assertEquals(201,post("/scenarios",map("name","夏の終わりに")).status);assertEquals(201,post("/persons",map("displayName","同名の人物")).status);assertEquals(201,post("/pcs",map("name","同名のPC","personId",1)).status);var t=table(2);t.put("tableDates",List.of(map("playedOn","2026-01-01"),map("playedOn","2026-01-01")));assertEquals(200,request("PUT","/tables/2",t,true).status);}
 @Test void formalFieldsRemainExact(){assertEquals(0,jdbc.queryForObject("select count(*) from information_schema.columns where table_name='pc' and column_name='game_system'",Integer.class));assertEquals("text",jdbc.queryForObject("select data_type from information_schema.columns where table_name='participation' and column_name='display_quote'",String.class));}
 @Test void databaseOwnershipAndPcRequiredForState(){assertThrows(Exception.class,()->jdbc.update("insert into pc(user_id,person_id,name) values(1,13,'wrong')"));long p=jdbc.queryForObject("select id from participation where pc_id is null limit 1",Long.class);assertThrows(Exception.class,()->jdbc.update("insert into end_pc_state(participation_id,status_values) values(?, '{}'::jsonb)",p));}
 @Test void pcSettingsOmittedEmptyFullAndVersion()throws Exception{var p=get("/pcs/1").body;int initial=list(p.get("systemSettings")).size();var r=patch("/pcs/1",map("version",p.get("version"),"name","changed"));assertEquals(200,r.status,r.raw);assertEquals(initial,list(r.body.get("systemSettings")).size());r=patch("/pcs/1",map("version",r.body.get("version"),"systemSettings",List.of()));assertEquals(200,r.status,r.raw);assertTrue(list(r.body.get("systemSettings")).isEmpty());assertTrue(number(r.body.get("version"))>number(p.get("version")));}
 @Test void duplicateCanonicalRejectedUnknownNotDeduplicated()throws Exception{var known=map("gameSystemName","クトゥルフ神話TRPG 7版","canonicalSystemKey","coc_7e","profileKey","coc_7e_v1","profileValues",map(),"displayOrder",1);code(post("/pcs",map("name","x","personId",1,"systemSettings",List.of(known,known))),400,"VALIDATION_ERROR");var unknown=map("gameSystemName","Custom","canonicalSystemKey",null,"profileKey",null,"profileValues",map(),"displayOrder",1);var r=post("/pcs",map("name","x","personId",1,"systemSettings",List.of(unknown,unknown)));assertEquals(201,r.status,r.raw);assertEquals(2,list(r.body.get("systemSettings")).size());}
 @Test void deleteConditions()throws Exception{code(request("DELETE","/scenarios/1",null,true),409,"CONFLICT");code(request("DELETE","/pcs/1",null,true),409,"CONFLICT");assertEquals(409,request("DELETE","/persons/1",null,true).status);}
 @Test void tableParentChildMembership()throws Exception{var t=table(3);var other=table(5);t.put("tableDates",other.get("tableDates"));code(request("PUT","/tables/3",t,true),404,"NOT_FOUND");assertEquals(table(3).get("version"),t.get("version"));}
 @Test void tableVersionConflictAndConcurrentMutation()throws Exception{var t=table(3);try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var a=pool.submit(()->request("PUT","/tables/3",t,true));var b=pool.submit(()->request("PUT","/tables/3",t,true));var statuses=List.of(a.get().status,b.get().status);assertTrue(statuses.contains(200),statuses.toString());assertTrue(statuses.contains(409),statuses.toString());}}
 @Test void pcDetachDeletesStateAtomically()throws Exception{var t=table(5);var parts=list(t.get("participations"));var p=parts.stream().filter(x->x.get("endPcState")!=null).findFirst().orElseThrow();long pid=number(p.get("id"));p.put("pcId",null);p.put("endPcState",null);t.put("participations",parts);var r=request("PUT","/tables/5",t,true);assertEquals(200,r.status,r.raw);assertEquals(0,jdbc.queryForObject("select count(*) from end_pc_state where participation_id=?",Integer.class,pid));}
 @Test void invalidTableSaveRollsBackPcStateDeletion()throws Exception{var t=table(5);var parts=list(t.get("participations"));var p=parts.stream().filter(x->x.get("endPcState")!=null).findFirst().orElseThrow();long pid=number(p.get("id"));p.put("pcId",null);p.put("endPcState",null);parts.getLast().put("displayQuote","a".repeat(25));t.put("participations",parts);assertEquals(400,request("PUT","/tables/5",t,true).status);assertEquals(1,jdbc.queryForObject("select count(*) from end_pc_state where participation_id=?",Integer.class,pid));}
 @Test void quoteExtendedGraphemeAndSpotlight()throws Exception{var t=table(3);var parts=list(t.get("participations"));parts.getLast().put("displayQuote","👨‍👩‍👧‍👦".repeat(24));parts.getLast().put("ho",null);parts.getLast().put("spotlightType","HO");t.put("participations",parts);var r=request("PUT","/tables/3",t,true);assertEquals(200,r.status,r.raw);assertEquals("QUOTE",list(r.body.get("participations")).getLast().get("spotlightType"));}
 @Test void savedProfileKeySurvivesScenarioChange()throws Exception{var sc=get("/scenarios/1").body;assertEquals(200,patch("/scenarios/1",map("version",sc.get("version"),"gameSystem","エモクロアTRPG")).status);var t=table(5);assertEquals(200,request("PUT","/tables/5",t,true).status);assertTrue(list(table(5).get("participations")).stream().filter(p->p.get("endPcState")!=null).allMatch(p->"coc_7e_v1".equals(obj(p.get("endPcState")).get("profileKey"))));}
 @Test void plChangeDoesNotRewritePastAutomatically()throws Exception{long before=jdbc.queryForObject("select person_id from participation where pc_id=1 limit 1",Long.class);var p=get("/pcs/1").body;assertEquals(200,post("/pcs/1/change-person",map("pcVersion",p.get("version"),"newPersonId",2,"participationUpdates",List.of())).status);assertEquals(before,jdbc.queryForObject("select person_id from participation where pc_id=1 limit 1",Long.class));}
 @Test void plChangeAllRollbackOnOneConflict()throws Exception{var ctx=get("/pcs/1/change-person-context").body;var updates=list(ctx.get("participations")).stream().limit(2).map(x->map("participationId",x.get("participationId"),"participationVersion",x.get("participationVersion"),"tableId",x.get("tableId"),"tableVersion",x.get("tableVersion"))).toList();updates.getLast().put("tableVersion",999);code(post("/pcs/1/change-person",map("pcVersion",obj(ctx.get("pc")).get("version"),"newPersonId",2,"participationUpdates",updates)),409,"OPTIMISTIC_LOCK_CONFLICT");assertEquals(1,jdbc.queryForObject("select person_id from pc where id=1",Integer.class));}
 @Test void activeProfilesResolverAndOptions()throws Exception{var res=get("/game-system-profiles");var arr=(List<?>)jp.takukairo.common.Json.MAPPER.readValue(res.raw,List.class);assertEquals(3,arr.size());var emo=get("/game-system-profiles/emoklore_v1").body;assertEquals(47,list(list(emo.get("optionSources")).getFirst().get("options")).size());for(String name:List.of("クトゥルフ神話TRPG 6版","クトゥルフ神話TRPG 7版","エモクロアTRPG"))assertEquals("EXACT",post("/game-systems/resolve",map("gameSystem",name)).body.get("state"));assertEquals("UNKNOWN",post("/game-systems/resolve",map("gameSystem","CoC")).body.get("state"));}
 @Test void previousCandidateExactProfileCurrentExcludedNoHistory200()throws Exception{var r=post("/pcs/1/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of("2027-01-01"),"targetTableId",5));assertEquals(200,r.status,r.raw);assertNotEquals(5L,number(obj(r.body.get("candidate")).get("sourceTableId")));assertEquals("coc_7e_v1",obj(r.body.get("candidate")).get("profileKey"));assertFalse(obj(r.body.get("candidate")).containsKey("growth"));assertEquals(200,post("/pcs/14/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of())).status);}
 @Test void ccfoliaMappingUnknownAndInvalid()throws Exception{String raw=write(map("kind","character","data",map("name","x","status",List.of(map("label","SAN","value",42,"max",99),map("label","HP","value",-1,"max",10)))));var r=post("/ccfolia/character-preview",map("rawText",raw,"scenarioId",1));assertEquals(200,r.status,r.raw);assertEquals(42,number(obj(obj(r.body.get("endPcStateCandidate")).get("statusValues")).get("san")));assertEquals(true,obj(r.body.get("endPcStateCandidate")).get("applicable"));r=post("/ccfolia/character-preview",map("rawText",raw));assertEquals(false,obj(r.body.get("endPcStateCandidate")).get("applicable"));assertTrue(list(r.body.get("warnings")).isEmpty());code(post("/ccfolia/character-preview",map("rawText","{")),400,"VALIDATION_ERROR");code(post("/ccfolia/character-preview",map("rawText",write(map("kind","other")))),400,"VALIDATION_ERROR");}
 @Test void ccfoliaEmokloreMismatchAndDuplicateMemo()throws Exception{String raw=write(map("kind","character","data",map("memo","共鳴感情・表: 喜び\n共鳴感情・表: 怒り","status",List.of(map("label","共鳴","value",10),map("label","HP","value",4)))));var r=post("/ccfolia/character-preview",map("rawText",raw,"scenarioId",1));assertEquals(false,obj(r.body.get("endPcStateCandidate")).get("applicable"));assertTrue(list(r.body.get("warnings")).stream().anyMatch(w->"PROFILE_MISMATCH".equals(w.get("code"))));}
 @Test void ccfoliaMaximumEscapedBodyAnd413Separate()throws Exception{String raw="{\"kind\":\"character\",\"data\":{\"memo\":\""+"a".repeat(2_097_103)+"\"}}";assertTrue(raw.getBytes(StandardCharsets.UTF_8).length<=2_097_152);assertEquals(200,post("/ccfolia/character-preview",map("rawText",raw)).status);code(post("/ccfolia/character-preview",map("rawText","x".repeat(2_097_153))),400,"VALIDATION_ERROR");var r=post("/ccfolia/character-preview",map("rawText","x".repeat(16_777_216)));code(r,413,"PAYLOAD_TOO_LARGE");assertTrue(list(r.body.get("fieldErrors")).isEmpty());}
 @Test void importSourceChangeResetsAnalysis()throws Exception{long sid=number(session().get("id"));analyze(sid,"シナリオ: test");assertEquals(1,number(get("/import/session/"+sid+"/review").body.containsKey("summary")?obj(get("/import/session/"+sid+"/review").body.get("summary")).get("total"):0));assertEquals(201,post("/import/session/"+sid+"/sources/text",map("expectedSessionVersion",version(sid),"text","new")).status);assertEquals(0,number(obj(get("/import/session/"+sid+"/review").body.get("summary")).get("total")));}
 @Test void importCandidateVersionAndSessionMembership()throws Exception{long sid=number(session().get("id"));long cid=number(analyze(sid,"シナリオ: test").getFirst().get("candidateId"));code(patch("/import/session/"+sid+"/candidates/"+cid,map("expectedSessionVersion",version(sid),"expectedVersion",999)),409,"IMPORT_CANDIDATE_VERSION_CONFLICT");code(get("/import/session/999/candidates/"+cid),404,"NOT_FOUND");}
 @Test void importResolutionReloadClearAndSharedIdentity()throws Exception{long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\n\nシナリオ: B");long a=number(rows.getFirst().get("candidateId")),b=number(rows.getLast().get("candidateId"));assertEquals(200,candidatePatch(sid,a,map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name","shared"))))).status);long rid=number(obj(candidate(sid,a).get("resolutionRefs")).get("scenarioResolutionId"));assertEquals(200,candidatePatch(sid,b,map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"useResolutionId",rid)))).status);assertEquals(200,candidatePatch(sid,a,map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"clearResolution",true)))).status);assertNull(obj(candidate(sid,a).get("resolutionRefs")).get("scenarioResolutionId"));assertEquals(rid,number(obj(candidate(sid,b).get("resolutionRefs")).get("scenarioResolutionId")));assertEquals(1,jdbc.queryForObject("select count(*) from import_resolution",Integer.class));}
 @Test void importPreviewIsNonDestructiveAndStalePriority()throws Exception{long sid=number(session().get("id"));var row=analyze(sid,"シナリオ: A").getFirst();long cid=number(row.get("candidateId"));var body=map("expectedSessionVersion",version(sid),"targets",List.of(map("candidateId",cid,"expectedVersion",row.get("version"))),"operation",map("type","EXCLUDE"));var prev=post("/import/session/"+sid+"/bulk-apply/preview",body);assertEquals(200,prev.status,prev.raw);assertEquals(true,candidate(sid,cid).get("registrationTarget"));assertEquals(200,candidatePatch(sid,cid,map("confirmationStatus","CHECKED")).status);body.put("previewRevision",prev.body.get("previewRevision"));code(post("/import/session/"+sid+"/bulk-apply",body),409,"IMPORT_PREVIEW_STALE");body.remove("previewRevision");code(post("/import/session/"+sid+"/bulk-apply/preview",body),409,"OPTIMISTIC_LOCK_CONFLICT");}
 @Test void importPartialRegisterDoubleAndPostRegisterLocks()throws Exception{long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\n\nシナリオ: B");long a=number(rows.getFirst().get("candidateId")),b=number(rows.getLast().get("candidateId"));assertEquals(200,candidatePatch(sid,a,map("confirmationStatus","CHECKED","resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name","registered"))))).status);candidatePatch(sid,b,map("confirmationStatus","CHECKED"));var r=post("/import/session/"+sid+"/register",map("expectedSessionVersion",version(sid),"candidates",List.of(map("candidateId",a,"expectedVersion",candidate(sid,a).get("version")),map("candidateId",b,"expectedVersion",candidate(sid,b).get("version")))));assertEquals(200,r.status,r.raw);assertEquals(List.of("REGISTERED","FAILED"),list(r.body.get("results")).stream().map(x->x.get("outcome")).toList());assertEquals(409,candidatePatch(sid,a,map("registrationTarget",false)).status);assertEquals(409,post("/import/session/"+sid+"/analyze",map("expectedSessionVersion",version(sid))).status);assertEquals(409,post("/import/session/"+sid+"/register",map("expectedSessionVersion",version(sid),"candidates",List.of(map("candidateId",a,"expectedVersion",candidate(sid,a).get("version"))))).status);assertEquals(409,post("/import/session/"+sid+"/complete",map("expectedSessionVersion",version(sid))).status);}
 @Autowired jp.takukairo.image.Cleanup cleanup;
 @org.springframework.test.context.bean.override.mockito.MockitoSpyBean jp.takukairo.image.LocalStorage storage;
 @AfterEach void clearMocks(){org.mockito.Mockito.reset(storage);}
 record Upload(String name,byte[] bytes){}
 Result multipart(String method,String path,String field,List<Upload> uploads,long expected)throws Exception{String boundary="TakukairoBoundary";var out=new java.io.ByteArrayOutputStream();out.write(("--"+boundary+"\r\nContent-Disposition: form-data; name=\""+(path.endsWith("/image")?"expectedVersion":"expectedSessionVersion")+"\"\r\n\r\n"+expected+"\r\n").getBytes(StandardCharsets.UTF_8));if(path.startsWith("/pcs/")&&path.endsWith("/image")){for(String key:List.of("positionX","positionY","zoom"))out.write(("--"+boundary+"\r\nContent-Disposition: form-data; name=\""+key+"\"\r\n\r\n"+(key.equals("zoom")?"1":"0")+"\r\n").getBytes(StandardCharsets.UTF_8));}for(var f:uploads){out.write(("--"+boundary+"\r\nContent-Disposition: form-data; name=\""+field+"\"; filename=\""+f.name+"\"\r\nContent-Type: application/octet-stream\r\n\r\n").getBytes(StandardCharsets.UTF_8));out.write(f.bytes);out.write("\r\n".getBytes());}out.write(("--"+boundary+"--\r\n").getBytes());var req=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api"+path)).header("X-CSRF-TOKEN",token).header("Content-Type","multipart/form-data; boundary="+boundary).method(method,HttpRequest.BodyPublishers.ofByteArray(out.toByteArray())).build();var res=client.send(req,HttpResponse.BodyHandlers.ofString());Map<String,Object> json;try{json=object(res.body());}catch(Exception e){json=map();}return new Result(res.statusCode(),json,res.body(),res);}
 Result file(long sid,long source,String name,int bytes)throws Exception{return multipart("PUT","/import/session/"+sid+"/sources/"+source+"/file","file",List.of(new Upload(name,new byte[bytes])),version(sid));}
 @Test void twentyFilesReplacementKeepsIdOrderAndFinalCapacity()throws Exception{long sid=number(session().get("id"));var files=new ArrayList<Upload>();for(int i=0;i<20;i++)files.add(new Upload("old"+i+".txt",new byte[16]));var r=multipart("POST","/import/session/"+sid+"/sources/files","files",files,version(sid));assertEquals(201,r.status,r.raw);var sources=list(get("/import/session/"+sid).body.get("sources"));long source=number(sources.getFirst().get("id"));var order=sources.getFirst().get("order");assertEquals(200,file(sid,source,"new.txt",32).status);var after=list(get("/import/session/"+sid).body.get("sources"));assertEquals(20,after.size());assertEquals(source,number(after.getFirst().get("id")));assertEquals(order,after.getFirst().get("order"));assertEquals("new.txt",after.getFirst().get("originalFileName"));assertEquals(1,jdbc.queryForObject("select count(*) from storage_delete_task",Integer.class));}
 @Test void fileFailurePreservesOldAndErrorPriority()throws Exception{long sid=number(session().get("id"));var r=multipart("POST","/import/session/"+sid+"/sources/files","files",List.of(new Upload("old.txt",new byte[1])),version(sid));long source=number(((List<?>)r.body.get("sourceIds")).getFirst());long v=version(sid);code(file(sid,source,"huge.txt",(int)jp.takukairo.importsession.ImportLimits.FILE+1),400,"VALIDATION_ERROR");assertEquals(v,version(sid));assertEquals("old.txt",list(get("/import/session/"+sid).body.get("sources")).getFirst().get("originalFileName"));code(multipart("PUT","/import/session/"+sid+"/sources/999/file","file",List.of(new Upload("x.txt",new byte[1])),v-1),409,"OPTIMISTIC_LOCK_CONFLICT");code(multipart("PUT","/import/session/"+sid+"/sources/999/file","file",List.of(new Upload("x.txt",new byte[1])),v),404,"NOT_FOUND");}
 @Test void replacementStorageFailurePreservesOldAndVersion()throws Exception{long sid=number(session().get("id"));var r=multipart("POST","/import/session/"+sid+"/sources/files","files",List.of(new Upload("old.txt",new byte[1])),version(sid));long source=number(((List<?>)r.body.get("sourceIds")).getFirst());long before=version(sid);org.mockito.Mockito.doThrow(new java.io.IOException("test failure")).when(storage).save(org.mockito.ArgumentMatchers.any(byte[].class),org.mockito.ArgumentMatchers.eq("raw"));code(file(sid,source,"new.txt",2),500,"INTERNAL_ERROR");assertEquals(before,version(sid));assertEquals("old.txt",list(get("/import/session/"+sid).body.get("sources")).getFirst().get("originalFileName"));}
 @Test void noOpReplacementStillIncrementsAndCleanupRetries()throws Exception{long sid=number(session().get("id"));var r=multipart("POST","/import/session/"+sid+"/sources/files","files",List.of(new Upload("old.txt",new byte[1])),version(sid));long source=number(((List<?>)r.body.get("sourceIds")).getFirst());long before=version(sid);assertEquals(200,file(sid,source,"old.txt",1).status);assertEquals(before+1,version(sid));String key=jdbc.queryForObject("select object_key from storage_delete_task limit 1",String.class);org.mockito.Mockito.doThrow(new java.io.IOException("test failure")).when(storage).delete(key);cleanup.run();assertEquals(1,jdbc.queryForObject("select attempt_count from storage_delete_task limit 1",Integer.class));assertTrue(jdbc.queryForObject("select next_attempt_at > now() from storage_delete_task limit 1",Boolean.class));org.mockito.Mockito.reset(storage);jdbc.execute("update storage_delete_task set next_attempt_at=now()-interval '1 minute'-interval '1 second'");cleanup.run();assertEquals(0,jdbc.queryForObject("select count(*) from storage_delete_task",Integer.class));}
 @Test void splitRequiresExplicitMappingAndCopiesTraces()throws Exception{long sid=number(session().get("id"));long cid=number(analyze(sid,"シナリオ: A").getFirst().get("candidateId"));candidatePatch(sid,cid,map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","REUSE_EXISTING","existingEntityId",1))));long rid=number(obj(candidate(sid,cid).get("resolutionRefs")).get("scenarioResolutionId"));var parts=new ArrayList<Map<String,Object>>();parts.add(map("clientPartKey","a","candidateData",draft("A"),"resolutionBindings",List.of()));parts.add(map("clientPartKey","b","candidateData",draft("B"),"resolutionBindings",List.of()));var body=map("expectedSessionVersion",version(sid),"expectedVersion",candidate(sid,cid).get("version"),"parts",parts);var preview=post("/import/session/"+sid+"/candidates/"+cid+"/split-preview",body);assertEquals(200,preview.status,preview.raw);assertEquals(false,list(preview.body.get("resultingCandidates")).getFirst().get("canApply"));parts.getFirst().put("resolutionBindings",List.of(map("slot",map("type","SCENARIO"),"resolutionId",rid)));preview=post("/import/session/"+sid+"/candidates/"+cid+"/split-preview",body);body.put("previewRevision",preview.body.get("previewRevision"));assertEquals(200,post("/import/session/"+sid+"/candidates/"+cid+"/split",body).status);assertEquals(2,jdbc.queryForObject("select count(*) from import_candidate",Integer.class));assertEquals(2,jdbc.queryForObject("select count(*) from import_candidate_source_trace",Integer.class));assertEquals(1,jdbc.queryForObject("select count(*) from import_resolution",Integer.class));}
 @Test void mergeMixedTargetNeedsChoiceAndDuplicateKeyRejected()throws Exception{long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\n\nシナリオ: B");long a=number(rows.getFirst().get("candidateId")),b=number(rows.getLast().get("candidateId"));candidatePatch(sid,b,map("registrationTarget",false));var body=map("expectedSessionVersion",version(sid),"sources",List.of(map("candidateId",a,"expectedVersion",candidate(sid,a).get("version")),map("candidateId",b,"expectedVersion",candidate(sid,b).get("version"))),"mergedCandidateData",draft("Merged"),"resolutionBindings",List.of(),"discardResolutionIds",List.of());var r=post("/import/session/"+sid+"/candidates/merge-preview",body);assertEquals(200,r.status,r.raw);assertEquals(true,r.body.get("registrationTargetConflict"));assertNull(obj(r.body.get("mergedCandidate")).get("registrationTarget"));assertEquals(false,r.body.get("canApply"));body.put("resultRegistrationTarget",true);r=post("/import/session/"+sid+"/candidates/merge-preview",body);assertEquals(true,r.body.get("canApply"));body.put("previewRevision",r.body.get("previewRevision"));assertEquals(200,post("/import/session/"+sid+"/candidates/merge",body).status);assertEquals(1,jdbc.queryForObject("select count(*) from import_candidate",Integer.class));}
 @Test void sharedResolutionRegisterCreatesOnce()throws Exception{long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\n\nシナリオ: B");long a=number(rows.getFirst().get("candidateId")),b=number(rows.getLast().get("candidateId"));candidatePatch(sid,a,map("confirmationStatus","CHECKED","resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name","shared")))));long rid=number(obj(candidate(sid,a).get("resolutionRefs")).get("scenarioResolutionId"));candidatePatch(sid,b,map("confirmationStatus","CHECKED","resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"useResolutionId",rid))));var r=post("/import/session/"+sid+"/register",map("expectedSessionVersion",version(sid),"candidates",List.of(map("candidateId",a,"expectedVersion",candidate(sid,a).get("version")),map("candidateId",b,"expectedVersion",candidate(sid,b).get("version")))));assertEquals(200,r.status,r.raw);assertTrue(list(r.body.get("results")).stream().allMatch(x->"REGISTERED".equals(x.get("outcome"))));assertEquals(1,jdbc.queryForObject("select count(*) from scenario where name='shared'",Integer.class));assertEquals(200,post("/import/session/"+sid+"/complete",map("expectedSessionVersion",version(sid))).status);assertEquals("null",get("/import/session/current").raw);}
 @Test void partialFailureRollsBackCreatedFormalEntities()throws Exception{long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\nPL: missing\n\nシナリオ: B");long a=number(rows.getFirst().get("candidateId")),b=number(rows.getLast().get("candidateId"));for(long cid:List.of(a,b))candidatePatch(sid,cid,map("confirmationStatus","CHECKED","resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name","unique"+cid)))));var r=post("/import/session/"+sid+"/register",map("expectedSessionVersion",version(sid),"candidates",List.of(map("candidateId",a,"expectedVersion",candidate(sid,a).get("version")),map("candidateId",b,"expectedVersion",candidate(sid,b).get("version")))));assertEquals(200,r.status,r.raw);assertEquals(List.of("FAILED","REGISTERED"),list(r.body.get("results")).stream().map(x->x.get("outcome")).toList());assertEquals(0,jdbc.queryForObject("select count(*) from scenario where name=?",Integer.class,"unique"+a));assertEquals(1,jdbc.queryForObject("select count(*) from scenario where name=?",Integer.class,"unique"+b));}
 @Test void staleResolutionSnapshotWinsApplyConflict()throws Exception{long sid=number(session().get("id"));long cid=number(analyze(sid,"シナリオ: A").getFirst().get("candidateId"));candidatePatch(sid,cid,map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","REUSE_EXISTING","existingEntityId",1))));var body=map("expectedSessionVersion",version(sid),"targets",List.of(map("candidateId",cid,"expectedVersion",candidate(sid,cid).get("version"))),"operation",map("type","CLEAR_RESOLUTION","slot",map("type","SCENARIO")));var prev=post("/import/session/"+sid+"/bulk-apply/preview",body);jdbc.execute("update import_resolution set version=version+1");body.put("previewRevision",prev.body.get("previewRevision"));code(post("/import/session/"+sid+"/bulk-apply",body),409,"IMPORT_PREVIEW_STALE");}
 @Autowired jp.takukairo.gamesystem.Profiles profiles;
 @org.springframework.test.context.bean.override.mockito.MockitoSpyBean jp.takukairo.image.LocalImageProcessor imageProcessor;
 byte[] png()throws Exception{var image=new java.awt.image.BufferedImage(32,48,java.awt.image.BufferedImage.TYPE_INT_ARGB);image.setRGB(1,1,0x80ff0000);var out=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"png",out);return out.toByteArray();}
 @SuppressWarnings("unchecked") List<Map<String,Object>> definitions(){return (List<Map<String,Object>>)org.springframework.test.util.ReflectionTestUtils.getField(profiles,"definitions");}
 @AfterEach void restoreProfiles()throws Exception{org.mockito.Mockito.reset(imageProcessor);try(var in=new ClassPathResource("config/profiles.json").getInputStream()){var fresh=jp.takukairo.common.Json.MAPPER.readValue(in,new com.fasterxml.jackson.core.type.TypeReference<List<Map<String,Object>>>(){});definitions().clear();definitions().addAll(fresh);}}
 @Test void safeImageUploadReplacementAndNoStorageKeyDto()throws Exception{var r=multipart("PUT","/pcs/1/image","file",List.of(new Upload("image.png",png())),0);assertEquals(200,r.status,r.raw);String old=jdbc.queryForObject("select image_master_key from pc where id=1",String.class);assertTrue(storage.exists(old));assertFalse(get("/pcs/1").raw.contains("imageMasterKey"));r=multipart("PUT","/pcs/1/image","file",List.of(new Upload("bad.png","bad".getBytes())),1);assertEquals(400,r.status,r.raw);assertEquals(old,jdbc.queryForObject("select image_master_key from pc where id=1",String.class));assertEquals(1,number(get("/pcs/1").body.get("version")));code(multipart("PUT","/pcs/1/image","file",List.of(new Upload("bad.png","bad".getBytes())),0),409,"OPTIMISTIC_LOCK_CONFLICT");}
 @Test void imageSecondVersionCheckAndCompensation()throws Exception{org.mockito.Mockito.doAnswer(call->{var processed=call.callRealMethod();try(var pool=Executors.newVirtualThreadPerTaskExecutor()){pool.submit(()->jdbc.update("update pc set version=version+1,name='concurrent' where id=1")).get();}return processed;}).when(imageProcessor).process(org.mockito.ArgumentMatchers.any(byte[].class));code(multipart("PUT","/pcs/1/image","file",List.of(new Upload("image.png",png())),0),409,"OPTIMISTIC_LOCK_CONFLICT");assertNull(jdbc.queryForObject("select image_master_key from pc where id=1",String.class));assertEquals("concurrent",get("/pcs/1").body.get("name"));}
 @Test void imageDeleteResetsPositionAndQueuesOldObjects()throws Exception{assertEquals(200,multipart("PUT","/pcs/1/image","file",List.of(new Upload("image.png",png())),0).status);assertEquals(200,patch("/pcs/1/image-transform",map("expectedVersion",1,"positionX",.125,"positionY",-.05,"zoom",1.5)).status);assertEquals(200,request("DELETE","/pcs/1/image?expectedVersion=2",null,true).status);var p=get("/pcs/1").body;assertNull(p.get("image"));assertEquals(2,jdbc.queryForObject("select count(*) from storage_delete_task",Integer.class));assertEquals(0,jdbc.queryForObject("select image_position_x from pc where id=1",java.math.BigDecimal.class).signum());}
 @Test void aggregateReorderUsesDeferredConstraint()throws Exception{var t=table(5);var parts=list(t.get("participations"));Collections.reverse(parts);t.put("participations",parts);var r=request("PUT","/tables/5",t,true);assertEquals(200,r.status,r.raw);assertEquals(1,number(list(r.body.get("participations")).stream().filter(p->p.get("role").equals("PL")).findFirst().orElseThrow().get("displayOrder")));}
 @Test void tableDeleteLeavesParentsAndDeletesChildren()throws Exception{long before=jdbc.queryForObject("select count(*) from pc",Long.class);assertEquals(204,request("DELETE","/tables/5",null,true).status);assertEquals(0,jdbc.queryForObject("select count(*) from participation where table_id=5",Integer.class));assertEquals(before,jdbc.queryForObject("select count(*) from pc",Long.class));assertEquals(200,get("/scenarios/1").status);}
 @Test void selectedPlChangesOnlyChosenAndKeepsPcState()throws Exception{var ctx=get("/pcs/1/change-person-context").body;var selected=list(ctx.get("participations")).getFirst();long before=jdbc.queryForObject("select count(*) from end_pc_state",Long.class);var req=map("participationId",selected.get("participationId"),"participationVersion",selected.get("participationVersion"),"tableId",selected.get("tableId"),"tableVersion",selected.get("tableVersion"));assertEquals(200,post("/pcs/1/change-person",map("pcVersion",obj(ctx.get("pc")).get("version"),"newPersonId",2,"participationUpdates",List.of(req))).status);assertEquals(2,jdbc.queryForObject("select person_id from participation where id=?",Integer.class,selected.get("participationId")));assertTrue(jdbc.queryForObject("select count(*) from participation where pc_id=1 and person_id=1",Integer.class)>0);assertEquals(before,jdbc.queryForObject("select count(*) from end_pc_state",Long.class));}
 @Test void activityCountsDistinctTablesNotRepeatedParticipations()throws Exception{var before=get("/activity/summary").body;jdbc.update("insert into participation(table_id,person_id,role,display_order,created_at,updated_at) values(5,1,'PL',10,now(),now())");assertEquals(before,get("/activity/summary").body);assertEquals(200,get("/activity/by-month?year=2026").status);assertEquals(200,get("/activity/by-year").status);}
 @Test void recentFavoriteAndSearchAreOwned()throws Exception{var recent=jp.takukairo.common.Json.MAPPER.readValue(get("/persons?recent=true").raw,List.class);assertTrue(recent.size()<=5);assertEquals(204,post("/scenarios/1/favorite",null).status);assertEquals(204,post("/scenarios/1/favorite",null).status);assertEquals(1,jdbc.queryForObject("select count(*) from scenario_favorite where user_id=1 and scenario_id=1",Integer.class));assertFalse(get("/scenarios?search=ownership").raw.contains("\"id\":11"));assertEquals(200,get("/scenarios?participation=PL&participation=KP&favorite=true").status);}
 @Test void inactiveProfileCanRemainButMigrationUnavailableHasExactPath()throws Exception{definitions().forEach(p->p.put("active",false));var pc=get("/pcs/1").body;var settings=list(pc.get("systemSettings"));assertEquals(200,patch("/pcs/1",map("version",pc.get("version"),"systemSettings",settings)).status);settings.getFirst().put("profileKey","unavailable_new_version");var r=patch("/pcs/1",map("version",1,"systemSettings",settings));code(r,400,"VALIDATION_ERROR");assertEquals("/systemSettings/0/profileKey",list(r.body.get("fieldErrors")).getFirst().get("path"));assertEquals("PROFILE_MIGRATION_NOT_AVAILABLE",list(r.body.get("fieldErrors")).getFirst().get("code"));assertEquals("coc_7e_v1",list(get("/pcs/1").body.get("systemSettings")).getFirst().get("profileKey"));}
 @Test void explicitActiveMigrationUpdatesPcButLeavesEndStates()throws Exception{var old=object(write(profiles.get("coc_7e_v1")));old.put("profileKey","coc_7e_old_test");old.put("active",false);definitions().add(old);jdbc.update("update pc_system_setting set profile_key='coc_7e_old_test' where pc_id=1");var pc=get("/pcs/1").body;var settings=list(pc.get("systemSettings"));settings.getFirst().put("profileKey","coc_7e_v1");assertEquals(200,patch("/pcs/1",map("version",pc.get("version"),"systemSettings",settings)).status);assertEquals(1,number(get("/pcs/1").body.get("version")));assertTrue(jdbc.queryForObject("select count(*) from end_pc_state where profile_key='coc_7e_v1'",Integer.class)>0);}
 @Test void emokloreMemoNfkcOptionsDuplicatesAndIgnoreMax()throws Exception{var profile=profiles.get("emoklore_v1");var option=list(list(profile.get("optionSources")).getFirst().get("options")).getFirst();String label=text(option.get("label")).replace('(', '（').replace(')', '）');String raw=write(map("kind","character","data",map("memo","共鳴感情・表： "+label+"\n共鳴感情・裏: "+label+"\n共鳴感情・裏: "+label,"status",List.of(map("label","ＨＰ","value",7,"max",99),map("label","共鳴","value",99)))));var r=post("/ccfolia/character-preview",map("rawText",raw,"manualProfileKey","emoklore_v1"));assertEquals(200,r.status,r.raw);assertEquals(option.get("key"),obj(obj(r.body.get("pcCandidate")).get("systemFields")).get("resonance_surface"));assertNull(obj(obj(r.body.get("pcCandidate")).get("systemFields")).get("resonance_hidden"));assertFalse(obj(obj(r.body.get("endPcStateCandidate")).get("statusValues")).containsKey("max"));assertTrue(list(r.body.get("warnings")).stream().anyMatch(w->w.get("code").equals("DUPLICATE_MEMO_KEY")));}
 @Test void importBusinessLimitsMultipleFieldErrorsAndNoVersionAdvance()throws Exception{long sid=number(session().get("id"));var files=new ArrayList<Upload>();for(int i=0;i<21;i++)files.add(new Upload("data"+i+".txt",new byte[2_500_000]));var r=multipart("POST","/import/session/"+sid+"/sources/files","files",files,version(sid));code(r,400,"VALIDATION_ERROR");assertEquals(List.of("IMPORT_FILE_COUNT_EXCEEDED","IMPORT_SESSION_SIZE_EXCEEDED"),list(r.body.get("fieldErrors")).stream().map(e->e.get("code")).toList());assertEquals(0,version(sid));assertTrue(list(get("/import/session/"+sid).body.get("sources")).isEmpty());}
 @Test void registeredFileLockOccursBeforeBusinessSizeLimit()throws Exception{long sid=number(session().get("id"));var upload=multipart("POST","/import/session/"+sid+"/sources/files","files",List.of(new Upload("a.txt","シナリオ: A".getBytes(StandardCharsets.UTF_8))),version(sid));long source=number(((List<?>)upload.body.get("sourceIds")).getFirst());post("/import/session/"+sid+"/analyze",map("expectedSessionVersion",version(sid)));long cid=number(list(get("/import/session/"+sid+"/review").body.get("items")).getFirst().get("candidateId"));candidatePatch(sid,cid,map("confirmationStatus","CHECKED","resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","REUSE_EXISTING","existingEntityId",1))));assertEquals(200,post("/import/session/"+sid+"/register",map("expectedSessionVersion",version(sid),"candidates",List.of(map("candidateId",cid,"expectedVersion",candidate(sid,cid).get("version"))))).status);code(file(sid,source,"huge.txt",(int)jp.takukairo.importsession.ImportLimits.FILE+1),409,"IMPORT_SOURCE_LOCKED_AFTER_REGISTRATION");}
 @Autowired jp.takukairo.importsession.ImportService imports;
 @Autowired jp.takukairo.gamesystem.CcfoliaMappingConfig mappingConfig;
 @Test void currentImportSerializesTimestampsAndAbsenceIsJsonNull()throws Exception{assertEquals("null",get("/import/session/current").raw);long sid=number(session().get("id"));var current=get("/import/session/current");assertEquals(200,current.status,current.raw);assertEquals(sid,number(current.body.get("id")));assertNotNull(current.body.get("savedAt"));assertNotNull(current.body.get("expiresAt"));}
 @Test void fullRawTextBoundaryAndUnicodeEscapeWorstCasePassBodyGuard()throws Exception{
  String base=write(map("kind","character","data",map("memo","")));int overhead=base.getBytes(StandardCharsets.UTF_8).length;String raw=write(map("kind","character","data",map("memo","a".repeat(2_097_152-overhead))));assertEquals(2_097_152,raw.getBytes(StandardCharsets.UTF_8).length);assertEquals(200,post("/ccfolia/character-preview",map("rawText",raw)).status);
  StringBuilder escaped=new StringBuilder("{\"rawText\":\"");for(char ch:raw.toCharArray())escaped.append(String.format(Locale.ROOT,"\\u%04x",(int)ch));escaped.append("\"}");assertTrue(escaped.length()>12_000_000);var request=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/ccfolia/character-preview")).header("X-CSRF-TOKEN",token).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(escaped.toString())).build();var r=client.send(request,HttpResponse.BodyHandlers.ofString());assertEquals(200,r.statusCode(),r.body());assertEquals(0,jdbc.queryForObject("select count(*) from import_source",Integer.class));
 }
 @Test void textBusinessBoundaryUsesTextAndVersionRemainsOnFailure()throws Exception{long sid=number(session().get("id"));assertEquals(201,post("/import/session/"+sid+"/sources/text",map("expectedSessionVersion",version(sid),"text","a".repeat(2_097_152))).status);long before=version(sid);var failed=post("/import/session/"+sid+"/sources/text",map("expectedSessionVersion",before,"text","a".repeat(2_097_153)));code(failed,400,"VALIDATION_ERROR");assertEquals("/text",list(failed.body.get("fieldErrors")).getFirst().get("path"));assertEquals(before,version(sid));}
 @Test void previousDatesFallbackTiesAndStatusOnly()throws Exception{jdbc.execute("delete from table_date");var p=post("/pcs/1/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of())).body;var c=obj(p.get("candidate"));assertEquals("CREATED_AT_FALLBACK",obj(c.get("basis")).get("type"));assertEquals("LOW",obj(c.get("basis")).get("confidence"));assertFalse(c.containsKey("growth"));assertNull(post("/pcs/1/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of("2027-01-01"))).body.get("candidate"));long table=number(c.get("sourceTableId"));jdbc.update("insert into table_date(table_id,played_on,created_at,updated_at) values(?,date '2026-01-01',now(),now()),(?,date '2026-12-01',now(),now())",table,table);assertNull(post("/pcs/1/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of("2026-06-01"))).body.get("candidate"));c=obj(post("/pcs/1/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of("2027-01-01"))).body.get("candidate"));assertEquals("HIGH",obj(c.get("basis")).get("confidence"));assertEquals("2026-12-01",obj(c.get("basis")).get("playedOn"));assertEquals("LOW",obj(obj(post("/pcs/1/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of())).body.get("candidate")).get("basis")).get("confidence"));}
 @Test void previousMalformedDateAndFractionalVersionAre400()throws Exception{code(post("/pcs/1/previous-end-state-candidate",map("scenarioId",1,"tableDates",List.of("bad"))),400,"VALIDATION_ERROR");code(patch("/pcs/1",map("version",0.5,"name","bad")),400,"MALFORMED_REQUEST");code(get("/scenarios/undefined"),400,"MALFORMED_REQUEST");}
 @Test void ccfoliaEachProfileMappingAndUnsupportedTrigger()throws Exception{String raw=write(map("kind","character","data",map("externalUrl","https://example.test/sheet","status",List.of(map("label","SAN","value",61,"max",99),map("label","HP","value",9),map("label","MP","value",6),map("label","共鳴","value",10)))));for(String key:List.of("coc_6e_v1","coc_7e_v1","emoklore_v1")){var r=post("/ccfolia/character-preview",map("rawText",raw,"manualProfileKey",key));assertEquals(200,r.status,r.raw);var values=obj(obj(r.body.get("endPcStateCandidate")).get("statusValues"));assertEquals(9,number(values.get("hp")));assertEquals(6,number(values.get("mp")));assertEquals(!key.equals("emoklore_v1"),values.containsKey("san"));assertFalse(values.containsKey("共鳴"));assertNull(r.body.get("detectedProfile"));assertFalse(list(r.body.get("warnings")).stream().anyMatch(w->w.get("code").equals("PROFILE_AMBIGUOUS")));}
  jdbc.update("update scenario set game_system=null where id=1");assertTrue(list(post("/ccfolia/character-preview",map("rawText",raw,"scenarioId",1)).body.get("warnings")).isEmpty());jdbc.update("update scenario set game_system='Custom' where id=1");assertTrue(list(post("/ccfolia/character-preview",map("rawText",raw,"scenarioId",1)).body.get("warnings")).stream().anyMatch(w->w.get("code").equals("UNSUPPORTED_GAME_SYSTEM")));definitions().getFirst().put("active",false);code(post("/ccfolia/character-preview",map("rawText",raw,"manualProfileKey","coc_6e_v1")),400,"VALIDATION_ERROR");}
 @Test void ccfoliaConflictingSpecificEvidenceBlocksProfileCandidates()throws Exception{var mappings=mappingConfig.mappings();var old=object(write(mappings.getFirst()));try{mappings.getFirst().put("memoMappings",map("六版専用","test"));String raw=write(map("kind","character","data",map("memo","六版専用: evidence\n共鳴感情・表: evidence","status",List.of(map("label","HP","value",4)))));var r=post("/ccfolia/character-preview",map("rawText",raw,"scenarioId",1));assertNull(r.body.get("detectedProfile"));assertTrue(list(r.body.get("warnings")).stream().anyMatch(w->w.get("code").equals("PROFILE_AMBIGUOUS")));assertTrue(obj(obj(r.body.get("pcCandidate")).get("systemFields")).isEmpty());assertTrue(obj(obj(r.body.get("endPcStateCandidate")).get("statusValues")).isEmpty());assertEquals(false,obj(r.body.get("endPcStateCandidate")).get("applicable"));}finally{mappings.getFirst().clear();mappings.getFirst().putAll(old);}}
 @Test void bulkResolutionApplyAndClearAreAtomicAndKeepSharedRows()throws Exception{long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\n\nシナリオ: B");var body=map("expectedSessionVersion",version(sid),"targets",rows.stream().map(r->map("candidateId",r.get("candidateId"),"expectedVersion",r.get("version"))).toList(),"operation",map("type","APPLY_RESOLUTION","slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name","shared")));var preview=post("/import/session/"+sid+"/bulk-apply/preview",body);assertEquals(200,preview.status,preview.raw);assertEquals(0,jdbc.queryForObject("select count(*) from import_resolution",Integer.class));body.put("previewRevision",preview.body.get("previewRevision"));assertEquals(200,post("/import/session/"+sid+"/bulk-apply",body).status);long a=number(rows.getFirst().get("candidateId")),b=number(rows.getLast().get("candidateId"));assertEquals(obj(candidate(sid,a).get("resolutionRefs")).get("scenarioResolutionId"),obj(candidate(sid,b).get("resolutionRefs")).get("scenarioResolutionId"));body=map("expectedSessionVersion",version(sid),"targets",List.of(map("candidateId",a,"expectedVersion",candidate(sid,a).get("version")),map("candidateId",b,"expectedVersion",candidate(sid,b).get("version"))),"operation",map("type","CLEAR_RESOLUTION","slot",map("type","SCENARIO")));preview=post("/import/session/"+sid+"/bulk-apply/preview",body);body.put("previewRevision",preview.body.get("previewRevision"));assertEquals(200,post("/import/session/"+sid+"/bulk-apply",body).status);assertNull(obj(candidate(sid,a).get("resolutionRefs")).get("scenarioResolutionId"));assertNull(obj(candidate(sid,b).get("resolutionRefs")).get("scenarioResolutionId"));assertEquals(1,jdbc.queryForObject("select count(*) from import_resolution",Integer.class));}
 @Test void resolutionBindingRejectsOtherSessionAndWrongType()throws Exception{long sid=number(session().get("id"));long cid=number(analyze(sid,"シナリオ: A").getFirst().get("candidateId"));candidatePatch(sid,cid,map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name","x")))));long rid=number(obj(candidate(sid,cid).get("resolutionRefs")).get("scenarioResolutionId"));var r=candidatePatch(sid,cid,map("candidateData",map("scenarioName","A","tableDates",List.of(),"participations",List.of(map("candidateParticipationKey","p","personName","x","role","PL")),"unassignedValues",List.of()),"resolutionChanges",List.of(map("slot",map("type","PERSON","candidateParticipationKey","p"),"useResolutionId",rid))));assertEquals(404,r.status,r.raw);jdbc.update("insert into import_session(user_id,status,current_step,saved_at,expires_at,created_at,updated_at) values(2,'ACTIVE','INPUT',now(),now()+interval '7 days',now(),now())");long foreign=jdbc.queryForObject("select id from import_session where user_id=2",Long.class);jdbc.update("insert into import_resolution(import_session_id,entity_type,decision,existing_entity_id,created_at,updated_at) values(?,'SCENARIO','REUSE_EXISTING',11,now(),now())",foreign);long foreignResolution=jdbc.queryForObject("select id from import_resolution where import_session_id=?",Long.class,foreign);assertEquals(404,candidatePatch(sid,cid,map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"useResolutionId",foreignResolution)))).status);code(get("/import/session/"+foreign+"/resolutions"),404,"NOT_FOUND");}
 @Test void expiredAndCompletedSessionCleanupLeavesFormalRecords()throws Exception{long sid=number(session().get("id"));long cid=number(analyze(sid,"シナリオ: Cleanup").getFirst().get("candidateId"));candidatePatch(sid,cid,map("confirmationStatus","CHECKED","resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name","retained")))));var r=post("/import/session/"+sid+"/register",map("expectedSessionVersion",version(sid),"candidates",List.of(map("candidateId",cid,"expectedVersion",candidate(sid,cid).get("version")))));long table=number(list(r.body.get("results")).getFirst().get("registeredTableId"));assertEquals(200,post("/import/session/"+sid+"/complete",map("expectedSessionVersion",version(sid))).status);jdbc.execute("update import_session set delete_after_at=now()-interval '1 second'");imports.expire();assertEquals(0,jdbc.queryForObject("select count(*) from import_session",Integer.class));assertEquals(200,get("/tables/"+table).status);sid=number(session().get("id"));multipart("POST","/import/session/"+sid+"/sources/files","files",List.of(new Upload("x.txt",new byte[]{1})),version(sid));jdbc.execute("update import_session set expires_at=now()-interval '1 second'");imports.expire();assertEquals(0,jdbc.queryForObject("select count(*) from import_source",Integer.class));assertEquals(1,jdbc.queryForObject("select count(*) from storage_delete_task",Integer.class));}
 @Test void cleanupCompensationFallbackAndDeadRetention()throws Exception{String key=storage.save(new byte[]{1},"raw");org.mockito.Mockito.doThrow(new java.io.IOException("test failure")).when(storage).delete(key);cleanup.compensate(key);assertEquals(1,jdbc.queryForObject("select count(*) from storage_delete_task",Integer.class));jdbc.execute("update storage_delete_task set created_at=now()-interval '31 days', next_attempt_at=now()-interval '1 minute'");cleanup.run();assertEquals("DEAD",jdbc.queryForObject("select status from storage_delete_task",String.class));}
 @Test void tableRoleChangeClearsPcSpecificFieldsAndDeleteAllChildren()throws Exception{var t=table(5);var parts=list(t.get("participations"));var pl=parts.stream().filter(p->p.get("role").equals("PL")&&p.get("pcId")!=null).findFirst().orElseThrow();long pid=number(pl.get("id"));pl.put("role","KP");pl.put("pcId",null);pl.put("ho",null);pl.put("displayQuote",null);pl.put("endPcState",null);assertEquals(200,request("PUT","/tables/5",t,true).status);assertEquals(0,jdbc.queryForObject("select count(*) from end_pc_state where participation_id=?",Integer.class,pid));assertEquals(204,request("DELETE","/tables/5",null,true).status);assertEquals(0,jdbc.queryForObject("select count(*) from participation where table_id=5",Integer.class));assertEquals(0,jdbc.queryForObject("select count(*) from table_date where table_id=5",Integer.class));}

 @Test void directDatabasePcDetachCannotLeaveExistingEndState(){long id=jdbc.queryForObject("select participation_id from end_pc_state limit 1",Long.class);assertThrows(Exception.class,()->jdbc.update("update participation set pc_id=null where id=?",id));assertNotNull(jdbc.queryForObject("select pc_id from participation where id=?",Long.class,id));}
 @Test void mergeConflictsRequireBindingOrExplicitDiscard()throws Exception{long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\n\nシナリオ: B");for(var row:rows)candidatePatch(sid,number(row.get("candidateId")),map("resolutionChanges",List.of(map("slot",map("type","SCENARIO"),"decision","CREATE_NEW","draftData",map("name",obj(row.get("summary")).get("scenarioName"))))));var body=map("expectedSessionVersion",version(sid),"sources",rows.stream().map(r->{long cid=number(r.get("candidateId"));try{return map("candidateId",cid,"expectedVersion",candidate(sid,cid).get("version"));}catch(Exception e){throw new RuntimeException(e);}}).toList(),"mergedCandidateData",draft("merged"),"resolutionBindings",List.of(),"discardResolutionIds",List.of());var r=post("/import/session/"+sid+"/candidates/merge-preview",body);assertEquals(false,r.body.get("canApply"));assertFalse(list(r.body.get("resolutionConflicts")).isEmpty());var ids=rows.stream().map(row->{try{return obj(candidate(sid,number(row.get("candidateId"))).get("resolutionRefs")).get("scenarioResolutionId");}catch(Exception e){throw new RuntimeException(e);}}).toList();body.put("discardResolutionIds",ids);r=post("/import/session/"+sid+"/candidates/merge-preview",body);assertEquals(true,r.body.get("canApply"),r.raw);body.put("previewRevision",r.body.get("previewRevision"));assertEquals(200,post("/import/session/"+sid+"/candidates/merge",body).status);assertEquals(1,jdbc.queryForObject("select count(*) from import_candidate",Integer.class));assertNull(obj(candidate(sid,jdbc.queryForObject("select id from import_candidate",Long.class)).get("resolutionRefs")).get("scenarioResolutionId"));}
 @Test void oldCsrfAfterLoginRotationIsRejected()throws Exception{String old=token;assertEquals(200,post("/dev/session",null).status);code(post("/persons",map("displayName","old csrf")),403,"FORBIDDEN");csrf();assertNotEquals(old,token);assertEquals(201,post("/persons",map("displayName","new csrf")).status);}

 @Test void pcSwapReplacesStateAtomicallyAndRoleErrorDoesNotMutate()throws Exception{
  var t=table(5);var parts=list(t.get("participations"));var p=parts.stream().filter(x->x.get("endPcState")!=null).findFirst().orElseThrow();long pid=number(p.get("id")),old=number(obj(p.get("endPcState")).get("id"));p.put("role","KP");code(request("PUT","/tables/5",t,true),400,"VALIDATION_ERROR");assertEquals(old,jdbc.queryForObject("select id from end_pc_state where participation_id=?",Long.class,pid));p.put("role","PL");p.put("pcId",14);p.put("endPcState",map("profileKey","coc_7e_v1","statusValues",map("hp",-3),"outcome",null,"growth",null,"aftereffects",null));var r=request("PUT","/tables/5",t,true);assertEquals(200,r.status,r.raw);assertNotEquals(old,jdbc.queryForObject("select id from end_pc_state where participation_id=?",Long.class,pid));assertEquals(14,jdbc.queryForObject("select pc_id from participation where id=?",Long.class,pid));assertEquals(-3,number(obj(obj(list(r.body.get("participations")).stream().filter(x->number(x.get("id"))==pid).findFirst().orElseThrow().get("endPcState")).get("statusValues")).get("hp")));
 }
 @Test void fileReplacementAtTwentyFilesAndExactFiftyMiBUsesFinalSize()throws Exception{
  long sid=number(session().get("id"));int size=2_621_440;var files=new ArrayList<Upload>();for(int i=0;i<20;i++)files.add(new Upload("boundary"+i+".txt",new byte[size]));var r=multipart("POST","/import/session/"+sid+"/sources/files","files",files,version(sid));assertEquals(201,r.status,r.raw);long source=number(((List<?>)r.body.get("sourceIds")).getFirst());assertEquals(200,file(sid,source,"replacement.txt",size).status);assertEquals(20,list(get("/import/session/"+sid).body.get("sources")).size());assertEquals(52_428_800L,jdbc.queryForObject("select sum(raw_byte_length) from import_source where import_session_id=?",Long.class,sid));long before=version(sid);var failed=file(sid,source,"too-much.txt",size+1);code(failed,400,"VALIDATION_ERROR");assertEquals("IMPORT_SESSION_SIZE_EXCEEDED",list(failed.body.get("fieldErrors")).getFirst().get("code"));assertEquals(before,version(sid));assertEquals("replacement.txt",jdbc.queryForObject("select original_file_name from import_source where id=?",String.class,source));
 }
 @Test void directTraceCannotPointToSourceInOtherSession()throws Exception{
  long sid=number(session().get("id"));analyze(sid,"シナリオ: A");long trace=jdbc.queryForObject("select id from import_candidate_source_trace limit 1",Long.class),old=jdbc.queryForObject("select import_source_id from import_candidate_source_trace where id=?",Long.class,trace);jdbc.execute("insert into import_session(user_id,status,current_step,saved_at,expires_at,created_at,updated_at) values(2,'ACTIVE','INPUT',now(),now()+interval '7 days',now(),now())");long other=jdbc.queryForObject("select id from import_session where user_id=2",Long.class);jdbc.update("insert into import_source(import_session_id,source_type,raw_text,raw_byte_length,source_order,created_at,updated_at) values(?,'PASTED_TEXT','x',1,1,now(),now())",other);long source=jdbc.queryForObject("select id from import_source where import_session_id=?",Long.class,other);assertThrows(Exception.class,()->jdbc.update("update import_candidate_source_trace set import_source_id=? where id=?",source,trace));assertEquals(old,jdbc.queryForObject("select import_source_id from import_candidate_source_trace where id=?",Long.class,trace));
 }
 @Test void mergeSameFalseTargetInheritedAndDuplicateParticipantKeysReject()throws Exception{
  long sid=number(session().get("id"));var rows=analyze(sid,"シナリオ: A\n\nシナリオ: B");for(var row:rows)candidatePatch(sid,number(row.get("candidateId")),map("registrationTarget",false));var body=map("expectedSessionVersion",version(sid),"sources",rows.stream().map(row->{try{long id=number(row.get("candidateId"));return map("candidateId",id,"expectedVersion",candidate(sid,id).get("version"));}catch(Exception e){throw new RuntimeException(e);}}).toList(),"mergedCandidateData",draft("Merged"),"resolutionBindings",List.of(),"discardResolutionIds",List.of());var r=post("/import/session/"+sid+"/candidates/merge-preview",body);assertEquals(false,obj(r.body.get("mergedCandidate")).get("registrationTarget"));assertEquals(true,r.body.get("canApply"));var duplicate=draft("Merged");duplicate.put("participations",List.of(map("candidateParticipationKey","same","personName","A","role","PL"),map("candidateParticipationKey","same","personName","B","role","PL")));body.put("mergedCandidateData",duplicate);code(post("/import/session/"+sid+"/candidates/merge-preview",body),400,"VALIDATION_ERROR");assertEquals(2,jdbc.queryForObject("select count(*) from import_candidate",Integer.class));
 }
 @Test void malformedAggregateCollectionsCannotSilentlyDeleteChildren()throws Exception{var pc=get("/pcs/1").body;long settings=jdbc.queryForObject("select count(*) from pc_system_setting where pc_id=1",Long.class);code(patch("/pcs/1",map("version",pc.get("version"),"systemSettings","wrong")),400,"MALFORMED_REQUEST");code(patch("/pcs/1",map("version",pc.get("version"),"systemSettings",List.of("wrong"))),400,"MALFORMED_REQUEST");assertEquals(settings,jdbc.queryForObject("select count(*) from pc_system_setting where pc_id=1",Long.class));var t=table(5);long parts=jdbc.queryForObject("select count(*) from participation where table_id=5",Long.class);t.put("participations","wrong");code(request("PUT","/tables/5",t,true),400,"MALFORMED_REQUEST");assertEquals(parts,jdbc.queryForObject("select count(*) from participation where table_id=5",Long.class));assertEquals(t.get("version"),table(5).get("version"));}
}
