package jp.takukairo;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import jp.takukairo.common.*;
import jp.takukairo.importsession.*;
import jp.takukairo.image.*;
import java.util.*;
import java.nio.charset.*;
import java.awt.image.BufferedImage;
import java.io.*;
import javax.imageio.ImageIO;
class LimitsParserImageTest {
 @Test void boundaryLimitsAndReplacementFinalState(){assertDoesNotThrow(()->ImportLimits.files(ImportLimits.SESSION,20,List.of(ImportLimits.FILE),true,ImportLimits.FILE));assertDoesNotThrow(()->ImportLimits.files(0,19,List.of(ImportLimits.FILE),false,0));assertDoesNotThrow(()->ImportLimits.text(0,0,ImportLimits.TEXT));assertThrows(ApiException.class,()->ImportLimits.text(0,0,ImportLimits.TEXT+1));assertThrows(ApiException.class,()->ImportLimits.files(0,20,List.of(1L),false,0));}
 @Test void allApplicableErrorsAndOrder(){var e=assertThrows(ApiException.class,()->ImportLimits.files(ImportLimits.SESSION,20,List.of(ImportLimits.FILE+1,ImportLimits.FILE+2),false,0));assertEquals(List.of("/files/0","/files/1","/sources","/sources"),e.fields.stream().map(ApiException.FieldError::path).toList());var t=assertThrows(ApiException.class,()->ImportLimits.text(ImportLimits.SESSION,0,ImportLimits.TEXT+1));assertEquals(2,t.fields.size());}
 @Test void parserFormatsPreserveUnknownAndCp932(){var p=new ImportParser();for(String ext:List.of(".txt",".md",".html")){String raw=ext.equals(".html")?"<p>シナリオ: A</p><p>未確定の記録</p>":"シナリオ: A\n未確定の記録";var parsed=p.parse("x"+ext,raw);assertEquals("A",parsed.getFirst().data().get("scenarioName"));assertFalse(Json.list(parsed.getFirst().data().get("unassignedValues")).isEmpty());}assertEquals("A",p.parse("x.csv","シナリオ名,PL\nA,人物").getFirst().data().get("scenarioName"));assertEquals("日本語",p.decode("日本語".getBytes(Charset.forName("windows-31j"))));assertThrows(ApiException.class,()->p.parse("x.pdf","text"));}
 @Test void imageMagicTransparencyAndDerivativeSize()throws Exception{var p=new LocalImageProcessor();assertThrows(ApiException.class,()->p.process("not png".getBytes()));var im=new BufferedImage(2200,100,BufferedImage.TYPE_INT_ARGB);im.setRGB(10,10,0x80ff0000);var raw=new ByteArrayOutputStream();ImageIO.write(im,"png",raw);var out=p.process(raw.toByteArray());assertEquals(2200,ImageIO.read(new ByteArrayInputStream(out.master())).getWidth());var derivative=ImageIO.read(new ByteArrayInputStream(out.derivative()));assertEquals(2048,derivative.getWidth());assertTrue(derivative.getColorModel().hasAlpha());}
 @Test void imageTooLargeAndAnimatedWebp(){var p=new LocalImageProcessor();assertThrows(ApiException.class,()->p.process(new byte[10*1024*1024+1]));byte[] animation=new byte[24];System.arraycopy("RIFF".getBytes(),0,animation,0,4);System.arraycopy("WEBPANIM".getBytes(),0,animation,8,8);assertThrows(ApiException.class,()->p.process(animation));}
 @Test void extendedGraphemeCounting(){assertEquals(24,Validation.graphemes("👨‍👩‍👧‍👦".repeat(24)));assertEquals(1,Validation.graphemes("か\u3099"));}
 @Test void genericSchemaValidatesAllInputTypesAndRetiredValues(){var profiles=new jp.takukairo.gamesystem.Profiles();var profile=profiles.get("emoklore_v1");var fields=List.of(Json.map("key","text","inputType","TEXT","required",true,"validation",Json.map("maxLength",4)),Json.map("key","integer","inputType","INTEGER","validation",Json.map("min",-1,"max",10)),Json.map("key","boolean","inputType","BOOLEAN"),Json.map("key","select","inputType","SELECT","optionSourceRef",Json.map("sourceKey","emoklore_resonance_emotions","revision",1)),Json.map("key","rows","inputType","REPEATER","validation",Json.map("maxItems",2),"itemFields",List.of(Json.map("key","select","inputType","SELECT","optionSourceRef",Json.map("sourceKey","emoklore_resonance_emotions","revision",1)))));profile.put("pcFields",fields);var options=Json.list(Json.list(profile.get("optionSources")).getFirst().get("options"));options.getFirst().put("selectable",false);var valid=Json.map("text","abcd","integer",-1,"boolean",false,"select","e02","rows",List.of(Json.map("select","e02")));assertDoesNotThrow(()->profiles.validateValues("emoklore_v1",valid,"/values",Map.of()));var bad=new LinkedHashMap<>(valid);bad.put("integer",1.5);assertThrows(ApiException.class,()->profiles.validateValues("emoklore_v1",bad,"/values",Map.of()));bad.put("integer",11);assertThrows(ApiException.class,()->profiles.validateValues("emoklore_v1",bad,"/values",Map.of()));bad.put("integer",0);bad.put("select","e01");assertThrows(ApiException.class,()->profiles.validateValues("emoklore_v1",bad,"/values",Map.of()));assertDoesNotThrow(()->profiles.validateValues("emoklore_v1",bad,"/values",Json.map("select","e01")));bad.put("rows",List.of("invalid"));assertThrows(ApiException.class,()->profiles.validateValues("emoklore_v1",bad,"/values",Json.map("select","e01")));bad.put("rows",List.of(Json.map("select","e01")));assertDoesNotThrow(()->profiles.validateValues("emoklore_v1",bad,"/values",Json.map("select","e01","rows",List.of(Json.map("select","e01")))));}
 @Test void oversizedHeaderIsRejectedBeforeRasterAllocation()throws Exception{var raw=new ByteArrayOutputStream();ImageIO.write(new BufferedImage(1,1,BufferedImage.TYPE_INT_RGB),"png",raw);for(int[] dims:List.of(new int[]{8193,1},new int[]{6000,6000})){byte[] bytes=raw.toByteArray();java.nio.ByteBuffer.wrap(bytes,16,8).putInt(dims[0]).putInt(dims[1]);var crc=new java.util.zip.CRC32();crc.update(bytes,12,17);java.nio.ByteBuffer.wrap(bytes,29,4).putInt((int)crc.getValue());assertThrows(ApiException.class,()->new LocalImageProcessor().process(bytes));}}
 @Test void jpegExifOrientationIsAppliedToMasterAndDerivative()throws Exception{var image=new BufferedImage(2,3,BufferedImage.TYPE_INT_RGB);var jpeg=new ByteArrayOutputStream();ImageIO.write(image,"jpeg",jpeg);var exif=new ByteArrayOutputStream();exif.write(new byte[]{'E','x','i','f',0,0});var tiff=java.nio.ByteBuffer.allocate(26).order(java.nio.ByteOrder.LITTLE_ENDIAN);tiff.put((byte)'I').put((byte)'I').putShort((short)42).putInt(8).putShort((short)1).putShort((short)0x0112).putShort((short)3).putInt(1).putShort((short)6).putShort((short)0).putInt(0);exif.write(tiff.array());byte[] original=jpeg.toByteArray();var input=new ByteArrayOutputStream();input.write(original,0,2);input.write(new byte[]{(byte)0xff,(byte)0xe1,0,(byte)(exif.size()+2)});input.write(exif.toByteArray());input.write(original,2,original.length-2);var out=new LocalImageProcessor().process(input.toByteArray());assertEquals(3,ImageIO.read(new ByteArrayInputStream(out.master())).getWidth());assertEquals(2,ImageIO.read(new ByteArrayInputStream(out.master())).getHeight());assertEquals(3,ImageIO.read(new ByteArrayInputStream(out.derivative())).getWidth());}

}
