package jp.takukairo.importsession;
import jp.takukairo.common.*;
import jp.takukairo.model.*;
import jp.takukairo.security.*;
import jp.takukairo.image.*;
import jp.takukairo.table.*;
import jp.takukairo.scenario.*;
import static jp.takukairo.common.Json.*;
import static jp.takukairo.common.Validation.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.*;
import org.springframework.web.multipart.MultipartFile;
import java.time.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
@Service @Transactional
public class ImportService {
 private final Store s;private final CurrentUser user;private final LocalStorage storage;private final Cleanup cleanup;private final ImportParser parser;private final LibraryService library;private final TableService tables;
 public ImportService(Store s,CurrentUser u,LocalStorage l,Cleanup c,ImportParser p,LibraryService lib,TableService t){this.s=s;user=u;storage=l;cleanup=c;parser=p;library=lib;tables=t;}
 private ImportSession owned(long id){return user.owned(ImportSession.class,id);}
 private ImportSession locked(long id,long expected){owned(id);var session=s.lock(ImportSession.class,id);Store.version(session.version,expected);if(!session.status.equals("ACTIVE"))throw new ApiException(409,"CONFLICT","このインポートは完了しています。");return session;}
 private ImportSource source(long id,long sourceId){var x=s.find(ImportSource.class,sourceId);if(!x.importSessionId.equals(id))throw ApiException.notFound();return x;}
 private ImportCandidate candidate(long id,long cid){var c=s.find(ImportCandidate.class,cid);if(!c.importSessionId.equals(id))throw ApiException.notFound();return c;}
 private List<ImportSource> sources(long id){return s.query(ImportSource.class,"where e.importSessionId=:id order by e.sourceOrder,e.id","id",id);}
 private List<ImportCandidate> candidates(long id){return s.query(ImportCandidate.class,"where e.importSessionId=:id order by e.id","id",id);}
 private void sourceGate(long id,boolean analysis){if(candidates(id).stream().anyMatch(c->c.registrationStatus.equals("REGISTERED")))throw new ApiException(409,analysis?"IMPORT_ANALYSIS_LOCKED_AFTER_REGISTRATION":"IMPORT_SOURCE_LOCKED_AFTER_REGISTRATION","登録済みのデータがあるため入力元を変更できません。");}
 private void editable(ImportCandidate c){if(c.registrationStatus.equals("REGISTERED"))throw new ApiException(409,"IMPORT_CANDIDATE_REGISTERED","登録済みのデータは正式データ側で編集してください。");}
 private void tick(ImportSession session){session.savedAt=Instant.now();session.expiresAt=session.savedAt.plus(Duration.ofDays(7));session.updatedAt=session.savedAt;s.flush();}
 private long bytes(long id){return sources(id).stream().mapToLong(x->x.rawByteLength).sum();}
 private void invalidate(long id){for(var c:candidates(id)){s.query(ImportCandidateSourceTrace.class,"where e.importCandidateId=:id","id",c.id).forEach(s::remove);s.remove(c);}s.query(ImportResolution.class,"where e.importSessionId=:id","id",id).forEach(s::remove);s.query(ImportPreview.class,"where e.importSessionId=:id","id",id).forEach(s::remove);}
 private void rollbackObject(String key){TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){public void afterCompletion(int status){if(status!=STATUS_COMMITTED)cleanup.compensate(key);}});}
 private String stage(byte[] data){try{String key=storage.save(data,"raw");rollbackObject(key);return key;}catch(Exception e){throw new ApiException(500,"INTERNAL_ERROR","ファイルを保存できませんでした。");}}
 public Map<String,Object> sessionDto(ImportSession x){return map("id",x.id,"version",x.version,"currentStep",x.currentStep,"status",x.status,"savedAt",x.savedAt,"expiresAt",x.expiresAt,"sources",sources(x.id).stream().map(v->map("id",v.id,"sourceType",v.sourceType,"originalFileName",v.originalFileName,"encoding",v.encoding,"rawText",v.rawText,"order",v.sourceOrder)).toList());}
 public Object current(){return s.query(ImportSession.class,"where e.userId=:u and e.status='ACTIVE'","u",user.id()).stream().findFirst().map(this::sessionDto).orElse(null);}
 public Object create(){var u=s.lock(AppUser.class,user.id());if(!s.query(ImportSession.class,"where e.userId=:u and e.status='ACTIVE'","u",u.id).isEmpty())throw new ApiException(409,"IMPORT_CONFLICT","前回の途中データがあります。");var x=new ImportSession();x.userId=u.id;x.status="ACTIVE";x.currentStep="INPUT";x.savedAt=Instant.now();x.expiresAt=x.savedAt.plus(Duration.ofDays(7));s.save(x);s.flush();return sessionDto(x);}
 public Object get(long id){return sessionDto(owned(id));}
 public Object step(long id,Map<String,Object>b){var x=locked(id,requiredLong(b,"expectedSessionVersion"));String step=text(b.get("currentStep"));if(!Set.of("INPUT","REVIEW","DETAIL","REGISTER").contains(step==null?"":step))throw ApiException.invalid("/currentStep","INVALID_STEP","画面を確認してください。");x.currentStep=step;tick(x);return map("sessionVersion",x.version);}
 public void delete(long id,long version){var session=locked(id,version);for(var source:sources(id))cleanup.schedule(source.temporaryStorageKey);invalidate(id);sources(id).forEach(s::remove);s.remove(session);}
 public Object addText(long id,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));sourceGate(id,false);Object value=b.get("text");if(!(value instanceof String))throw ApiException.invalid("/text","REQUIRED","テキストを入力してください。");String text=(String)value;long size=text.getBytes(StandardCharsets.UTF_8).length;ImportLimits.text(bytes(id),0,size);var source=new ImportSource();source.importSessionId=id;source.sourceType="PASTED_TEXT";source.rawText=text;source.rawByteLength=size;source.sourceOrder=sources(id).stream().mapToInt(x->x.sourceOrder).max().orElse(0)+1;s.save(source);invalidate(id);tick(session);return map("sessionVersion",session.version,"sourceId",source.id);}
 public Object patchText(long id,long sourceId,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));var source=source(id,sourceId);sourceGate(id,false);if(!source.sourceType.equals("PASTED_TEXT"))throw new ApiException(409,"CONFLICT","ファイルの差し替え操作を使用してください。");if(b.containsKey("order"))throw new ApiException(400,"MALFORMED_REQUEST","入力元の並べ替えは利用できません。");if(!(b.get("text") instanceof String text))throw ApiException.invalid("/text","REQUIRED","テキストを入力してください。");long size=text.getBytes(StandardCharsets.UTF_8).length;ImportLimits.text(bytes(id),source.rawByteLength,size);source.rawText=text;source.rawByteLength=size;source.updatedAt=Instant.now();invalidate(id);tick(session);return map("sessionVersion",session.version);}
 public Object addFiles(long id,long expected,List<MultipartFile> files){var session=locked(id,expected);sourceGate(id,false);if(files.isEmpty())throw ApiException.invalid("/files","REQUIRED","ファイルを選択してください。");var old=sources(id);ImportLimits.files(bytes(id),(int)old.stream().filter(x->x.sourceType.equals("FILE")).count(),files.stream().map(MultipartFile::getSize).toList(),false,0);int order=old.stream().mapToInt(x->x.sourceOrder).max().orElse(0);var ids=new ArrayList<Long>();for(var f:files){var source=new ImportSource();source.importSessionId=id;source.sourceType="FILE";source.originalFileName=safeName(f.getOriginalFilename());source.sourceOrder=++order;source.rawByteLength=f.getSize();source.encoding="AUTO";try{source.temporaryStorageKey=stage(f.getBytes());}catch(java.io.IOException e){throw new ApiException(500,"INTERNAL_ERROR","ファイルを読み取れませんでした。");}s.save(source);ids.add(source.id);}invalidate(id);tick(session);return map("sessionVersion",session.version,"sourceIds",ids);}
 private String safeName(String name){String v=name==null?"file.txt":name.replace('\\','/');v=v.substring(v.lastIndexOf('/')+1);if(v.length()>255)throw ApiException.invalid("/file","TOO_LONG","ファイル名を短くしてください。");return v;}
 public Object replace(long id,long sourceId,long expected,List<MultipartFile> files){var session=locked(id,expected);var source=source(id,sourceId);sourceGate(id,false);if(!source.sourceType.equals("FILE"))throw new ApiException(409,"CONFLICT","この入力元はファイルではないため差し替えできません。");if(files.size()!=1)throw ApiException.invalid("/file","INVALID_COUNT","ファイルを1件選択してください。");var f=files.getFirst();String name=safeName(f.getOriginalFilename());ImportLimits.files(bytes(id),(int)sources(id).stream().filter(x->x.sourceType.equals("FILE")).count(),List.of(f.getSize()),true,source.rawByteLength);String next;try{next=stage(f.getBytes());}catch(java.io.IOException e){throw new ApiException(500,"INTERNAL_ERROR","ファイルを読み取れませんでした。");}cleanup.schedule(source.temporaryStorageKey);source.temporaryStorageKey=next;source.originalFileName=name;source.encoding="AUTO";source.rawByteLength=f.getSize();source.updatedAt=Instant.now();invalidate(id);tick(session);return map("sessionVersion",session.version,"sourceId",source.id);}
 public Object deleteSource(long id,long sourceId,long expected){var session=locked(id,expected);var source=source(id,sourceId);sourceGate(id,false);invalidate(id);cleanup.schedule(source.temporaryStorageKey);s.remove(source);tick(session);return map("sessionVersion",session.version);}
 public Object reset(long id,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));sourceGate(id,false);invalidate(id);session.currentStep="INPUT";tick(session);return map("sessionVersion",session.version);}
 public Object analyze(long id,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));sourceGate(id,true);invalidate(id);for(var source:sources(id)){String raw=source.rawText;if(raw==null){try{raw=parser.decode(storage.read(source.temporaryStorageKey));}catch(Exception e){throw new ApiException(500,"INTERNAL_ERROR","入力元を読み取れませんでした。");}}for(var parsed:parser.parse(source.originalFileName,raw)){var c=new ImportCandidate();c.importSessionId=id;c.candidateData=write(parsed.data());c.status=classify(parsed.data(),Map.of());c.confirmationStatus="UNCHECKED";c.registrationTarget=true;c.registrationStatus="PENDING";c.resolutionRefs=write(map("scenarioResolutionId",null,"participations",List.of()));s.save(c);s.flush();var trace=new ImportCandidateSourceTrace();trace.importCandidateId=c.id;trace.importSourceId=source.id;trace.sourceLocation=write(map("fieldPath","/table/scenarioName","lineStart",parsed.lineStart(),"lineEnd",parsed.lineEnd(),"excerpt",parsed.excerpt()));s.save(trace);}}session.currentStep="REVIEW";tick(session);return map("sessionVersion",session.version);}
 private String classify(Map<String,Object>d,Map<String,Object>refs){if(optional(d.get("scenarioName"))==null)return "NEEDS_FIX";if(list(d.get("unassignedValues")).stream().anyMatch(x->"UNASSIGNED".equals(obj(x.get("assignment")).get("type"))))return "NEEDS_REVIEW";if(refs.get("scenarioResolutionId")==null)return "NEEDS_REVIEW";for(var p:list(d.get("participations"))){var r=list(refs.get("participations")).stream().filter(x->Objects.equals(x.get("candidateParticipationKey"),p.get("candidateParticipationKey"))).findFirst().orElse(Map.of());if(r.get("personResolutionId")==null||optional(p.get("pcName"))!=null&&r.get("pcResolutionId")==null)return "NEEDS_REVIEW";}return "REGISTERABLE";}
 public Object review(long id,String status,int page,int size){var x=owned(id);var all=candidates(id);var filtered=all.stream().filter(c->status==null||c.status.equals(status)||c.registrationStatus.equals(status)).toList();int safeSize=Math.clamp(size,1,100),start=Math.clamp(page,0,Integer.MAX_VALUE);return map("sessionId",id,"sessionVersion",x.version,"summary",map("total",all.size(),"registerable",all.stream().filter(c->c.status.equals("REGISTERABLE")).count(),"needsReview",all.stream().filter(c->c.status.equals("NEEDS_REVIEW")).count(),"needsFix",all.stream().filter(c->c.status.equals("NEEDS_FIX")).count(),"checked",all.stream().filter(c->c.confirmationStatus.equals("CHECKED")).count()),"items",filtered.stream().skip((long)start*safeSize).limit(safeSize).map(c->map("candidateId",c.id,"version",c.version,"status",c.status,"confirmationStatus",c.confirmationStatus,"registrationTarget",c.registrationTarget,"registrationStatus",c.registrationStatus,"summary",object(c.candidateData))).toList());}
 private Map<String,Object> resolutionDto(ImportResolution r){return map("id",r.id,"version",r.version,"entityType",r.entityType,"decision",r.decision,"existingEntityId",r.existingEntityId,"createdEntityId",r.createdEntityId,"draftData",r.draftData==null?null:object(r.draftData));}
 private Set<Long> refIds(Map<String,Object> refs){Set<Long> ids=new LinkedHashSet<>();if(refs.get("scenarioResolutionId")!=null)ids.add(Json.id(refs.get("scenarioResolutionId")));for(var p:list(refs.get("participations")))for(String key:List.of("personResolutionId","pcResolutionId"))if(p.get(key)!=null)ids.add(Json.id(p.get(key)));return ids;}
 private List<Map<String,Object>> bundle(long id,Map<String,Object> refs){return refIds(refs).stream().map(r->resolution(id,r,null)).map(this::resolutionDto).toList();}
 private ImportResolution resolution(long id,long rid,String type){var r=s.find(ImportResolution.class,rid);if(!r.importSessionId.equals(id)||type!=null&&!r.entityType.equals(type))throw ApiException.notFound();return r;}
 public Object resolutions(long id,String type){var session=owned(id);return map("sessionId",id,"sessionVersion",session.version,"items",s.query(ImportResolution.class,"where e.importSessionId=:id order by e.id","id",id).stream().filter(r->type==null||r.entityType.equals(type)).map(this::resolutionDto).toList());}
 public Map<String,Object> detail(long id,long cid){owned(id);var c=candidate(id,cid);var refs=object(c.resolutionRefs);var contexts=s.query(ImportCandidateSourceTrace.class,"where e.importCandidateId=:id","id",cid).stream().map(t->{var src=source(id,t.importSourceId);return map("sourceId",src.id,"sourceType",src.sourceType,"originalFileName",src.originalFileName,"traces",List.of(object(t.sourceLocation)));}).toList();return map("candidate",map("id",c.id,"version",c.version,"candidateData",object(c.candidateData),"status",c.status,"confirmationStatus",c.confirmationStatus,"registrationTarget",c.registrationTarget,"registrationStatus",c.registrationStatus,"registrationResult",c.registrationResult==null?null:object(c.registrationResult),"resolutionRefs",refs),"resolutions",bundle(id,refs),"sourceContexts",contexts);}
 private void applyAssignments(Map<String,Object>d){for(var value:list(d.get("unassignedValues"))){var a=obj(value.get("assignment"));String type=text(a.get("type"));if(type!=null&&type.startsWith("PARTICIPATION_")){var part=list(d.get("participations")).stream().filter(p->Objects.equals(p.get("candidateParticipationKey"),a.get("candidateParticipationKey"))).findFirst().orElseThrow(()->ApiException.invalid("/candidateData/unassignedValues","INVALID_ASSIGNMENT","割り当てる参加者を選択してください。"));String field=switch(type){case "PARTICIPATION_PERSON"->"personName";case "PARTICIPATION_PC"->"pcName";case "PARTICIPATION_HANDOUT"->"handout";default->throw ApiException.invalid("/candidateData/unassignedValues","INVALID_ASSIGNMENT","値の扱いを確認してください。");};part.put(field,value.get("rawValue"));}}}
 private void validateDraft(Map<String,Object>d){name(d.get("scenarioName"),"/candidateData/scenarioName");Set<String> keys=new HashSet<>();for(var p:list(d.get("participations"))){String key=text(p.get("candidateParticipationKey"));if(key==null||!keys.add(key))throw ApiException.invalid("/candidateData/participations","DUPLICATE_KEY","人物の識別子を確認してください。");if(!Set.of("KP","PL").contains(text(p.get("role"))))throw ApiException.invalid("/candidateData/participations","INVALID_ROLE","役割を確認してください。");}for(var date:list(d.get("tableDates")))try{LocalDate.parse(text(date.get("playedOn")));}catch(Exception e){throw ApiException.invalid("/candidateData/tableDates","INVALID_DATE","日付を確認してください。");}url(d.get("recordingUrl"),"/candidateData/recordingUrl");String tableName=optional(d.get("tableName"));if(tableName!=null&&tableName.codePointCount(0,tableName.length())>255)throw ApiException.invalid("/candidateData/tableName","TOO_LONG","255文字以下にしてください。");}
 private Map<String,Object> refsFor(Map<String,Object>d){return map("scenarioResolutionId",null,"participations",list(d.get("participations")).stream().map(p->map("candidateParticipationKey",p.get("candidateParticipationKey"),"personResolutionId",null,"pcResolutionId",null)).toList());}
 private void bind(Map<String,Object>refs,Map<String,Object>d,Map<String,Object>slot,Long rid){String type=text(slot.get("type"));if("SCENARIO".equals(type)){refs.put("scenarioResolutionId",rid);return;}if(!Set.of("PERSON","PC").contains(type==null?"":type))throw ApiException.invalid("/resolutionChanges","INVALID_SLOT","照合先を確認してください。");String key=text(slot.get("candidateParticipationKey"));if(list(d.get("participations")).stream().noneMatch(p->Objects.equals(p.get("candidateParticipationKey"),key)))throw ApiException.invalid("/resolutionChanges","INVALID_SLOT","人物の照合先を確認してください。");var parts=new ArrayList<>(list(refs.get("participations")));var ref=parts.stream().filter(p->Objects.equals(p.get("candidateParticipationKey"),key)).findFirst().orElse(null);if(ref==null){ref=map("candidateParticipationKey",key,"personResolutionId",null,"pcResolutionId",null);parts.add(ref);refs.put("participations",parts);}ref.put(type.equals("PERSON")?"personResolutionId":"pcResolutionId",rid);}
 private void existing(String type,long id){switch(type){case "SCENARIO"->user.owned(Scenario.class,id);case "PERSON"->user.owned(Person.class,id);case "PC"->user.owned(Pc.class,id);default->throw ApiException.invalid("/resolutionChanges","INVALID_TYPE","照合種類を確認してください。");}}
 private Long changeResolution(long id,Map<String,Object>change,String type){int modes=(change.containsKey("decision")?1:0)+(change.containsKey("useResolutionId")?1:0)+(Boolean.TRUE.equals(change.get("clearResolution"))?1:0);if(modes!=1)throw ApiException.invalid("/resolutionChanges","INVALID_CHANGE","照合操作を1つ指定してください。");if(Boolean.TRUE.equals(change.get("clearResolution")))return null;if(change.containsKey("useResolutionId"))return resolution(id,requiredLong(change,"useResolutionId"),type).id;var r=new ImportResolution();r.importSessionId=id;r.entityType=type;r.decision=text(change.get("decision"));if("REUSE_EXISTING".equals(r.decision)){r.existingEntityId=requiredLong(change,"existingEntityId");existing(type,r.existingEntityId);r.draftData=null;}else if("CREATE_NEW".equals(r.decision)){var draft=obj(change.get("draftData"));name(draft.get(type.equals("PERSON")?"displayName":"name"),"/resolutionChanges/draftData");r.draftData=write(draft);}else throw ApiException.invalid("/resolutionChanges/decision","INVALID_DECISION","照合判断を確認してください。");s.save(r);s.flush();return r.id;}
 private void patchCandidate(ImportCandidate c,Map<String,Object>b){editable(c);var d=b.containsKey("candidateData")?obj(b.get("candidateData")):object(c.candidateData);var refs=object(c.resolutionRefs);for(var change:list(b.get("resolutionChanges"))){var slot=obj(change.get("slot"));Long rid=changeResolution(c.importSessionId,change,text(slot.get("type")));bind(refs,d,slot,rid);}if(b.containsKey("candidateData")){Set<String> keys=new HashSet<>();for(var p:list(d.get("participations"))){String k=text(p.get("candidateParticipationKey"));if(k==null||!keys.add(k))throw ApiException.invalid("/candidateData/participations","DUPLICATE_KEY","人物の識別子を確認してください。");}for(var p:list(refs.get("participations")))if(!keys.contains(text(p.get("candidateParticipationKey")))&&(p.get("personResolutionId")!=null||p.get("pcResolutionId")!=null))throw ApiException.invalid("/candidateData/participations","RESOLUTION_MAPPING_REQUIRED","人物を削除する前に照合判断を解除してください。");refs.put("participations",list(refs.get("participations")).stream().filter(p->keys.contains(text(p.get("candidateParticipationKey")))).toList());}if(b.containsKey("confirmationStatus")){String conf=text(b.get("confirmationStatus"));if(!Set.of("CHECKED","UNCHECKED").contains(conf))throw ApiException.invalid("/confirmationStatus","INVALID_STATUS","確認状態を選択してください。");c.confirmationStatus=conf;}if(b.containsKey("registrationTarget")){if(!(b.get("registrationTarget") instanceof Boolean))throw ApiException.invalid("/registrationTarget","INVALID_TYPE","登録対象を選択してください。");c.registrationTarget=(Boolean)b.get("registrationTarget");}c.registrationStatus=c.registrationTarget?"PENDING":"EXCLUDED";c.candidateData=write(d);c.resolutionRefs=write(refs);c.status=classify(d,refs);c.updatedAt=Instant.now();}
 public Object patch(long id,long cid,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));var c=candidate(id,cid);if(c.version!=requiredLong(b,"expectedVersion"))throw new ApiException(409,"IMPORT_CANDIDATE_VERSION_CONFLICT","確認後に内容が更新されています。");patchCandidate(c,b);tick(session);return map("sessionVersion",session.version,"candidate",obj(detail(id,cid).get("candidate")),"resolutions",detail(id,cid).get("resolutions"));}
 private void candidateVersion(ImportCandidate c,Map<String,Object>b){if(c.version!=requiredLong(b,"expectedVersion"))throw new ApiException(409,"IMPORT_CANDIDATE_VERSION_CONFLICT","確認後に内容が更新されています。");editable(c);}
 private Map<String,Object> snapshot(long id){return map("candidates",candidates(id).stream().map(c->map("id",c.id,"version",c.version)).toList(),"resolutions",s.query(ImportResolution.class,"where e.importSessionId=:id order by e.id","id",id).stream().map(r->map("id",r.id,"version",r.version)).toList());}
 private void validateBulkOperation(long id,Map<String,Object> operation){String type=text(operation.get("type"));if(type==null||!Set.of("APPLY_RESOLUTION","CLEAR_RESOLUTION","EXCLUDE","INCLUDE").contains(type))throw ApiException.invalid("/operation/type","INVALID_OPERATION","一括操作を確認してください。");if(type.equals("APPLY_RESOLUTION")){var slot=obj(operation.get("slot"));String entity=text(slot.get("type"));if(entity==null||!Set.of("SCENARIO","PERSON","PC").contains(entity))throw ApiException.invalid("/operation/slot","INVALID_SLOT","照合先を確認してください。");if(operation.containsKey("useResolutionId"))resolution(id,requiredLong(operation,"useResolutionId"),entity);else if("REUSE_EXISTING".equals(operation.get("decision")))existing(entity,requiredLong(operation,"existingEntityId"));else if("CREATE_NEW".equals(operation.get("decision")))name(obj(operation.get("draftData")).get(entity.equals("PERSON")?"displayName":"name"),"/operation/draftData");else throw ApiException.invalid("/operation/decision","INVALID_DECISION","照合判断を確認してください。");}}

 private Map<String,Object> payload(Map<String,Object>b){var p=new LinkedHashMap<>(b);p.remove("previewRevision");return p;}
 private Map<String,Object> explicitBindings(long id,Map<String,Object>d,List<Map<String,Object>> bindings){var refs=refsFor(d);Set<String> slots=new HashSet<>();for(var x:bindings){var slot=obj(x.get("slot"));String identity=write(slot);if(!slots.add(identity))throw ApiException.invalid("/resolutionBindings","DUPLICATE_SLOT","照合先を1つ指定してください。");var r=resolution(id,requiredLong(x,"resolutionId"),text(slot.get("type")));bind(refs,d,slot,r.id);}return refs;}
 public Object preview(long id,String kind,Long cid,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));var response=new LinkedHashMap<String,Object>();response.put("sessionVersion",session.version);response.put("previewRevision",UUID.randomUUID().toString());
  if(kind.equals("BULK")){var operation=obj(b.get("operation"));validateBulkOperation(id,operation);var targets=new ArrayList<Object>();Set<Long> unique=new HashSet<>();for(var x:list(b.get("targets"))){var c=candidate(id,requiredLong(x,"candidateId"));candidateVersion(c,x);if(!unique.add(c.id))throw ApiException.invalid("/targets","DUPLICATE","対象が重複しています。");String type=text(operation.get("type"));boolean willChange=true;if(type.equals("EXCLUDE"))willChange=c.registrationTarget;else if(type.equals("INCLUDE"))willChange=!c.registrationTarget;else{var slot=new LinkedHashMap<>(obj(operation.get("slot")));if(x.containsKey("candidateParticipationKey"))slot.put("candidateParticipationKey",x.get("candidateParticipationKey"));var refs=object(c.resolutionRefs);String before=write(refs);bind(refs,object(c.candidateData),slot,null);if(type.equals("CLEAR_RESOLUTION"))willChange=!before.equals(write(refs));}targets.add(map("candidateId",c.id,"version",c.version,"willChange",willChange));}if(targets.isEmpty())throw ApiException.invalid("/targets","REQUIRED","対象を選択してください。");response.put("affectedCount",targets.size());response.put("targets",targets);}
  else if(kind.equals("SPLIT")){var c=candidate(id,cid);candidateVersion(c,b);var parts=list(b.get("parts"));if(parts.size()<2)throw ApiException.invalid("/parts","INVALID_COUNT","2件以上に分割してください。");Set<Long> inherited=new HashSet<>();var results=new ArrayList<Map<String,Object>>();Set<String> keys=new HashSet<>();for(var part:parts){String key=text(part.get("clientPartKey"));if(key==null||!keys.add(key))throw ApiException.invalid("/parts","DUPLICATE_KEY","分割先の識別子を確認してください。");var d=obj(part.get("candidateData"));validateDraft(d);var refs=explicitBindings(id,d,list(part.get("resolutionBindings")));inherited.addAll(refIds(refs));results.add(map("clientPartKey",key,"candidateData",d,"resolutionRefs",refs,"resolutions",bundle(id,refs)));}var missing=refIds(object(c.resolutionRefs));missing.removeAll(inherited);for(var result:results){result.put("unmappedSourceResolutionRefs",missing);result.put("canApply",missing.isEmpty());}response.put("sourceCandidateId",cid);response.put("sourceVersion",c.version);response.put("resultingCandidates",results);}
  else if(kind.equals("MERGE")){var requests=list(b.get("sources"));if(requests.size()<2)throw ApiException.invalid("/sources","INVALID_COUNT","2件以上を選択してください。");var all=new ArrayList<ImportCandidate>();Set<Long> unique=new HashSet<>();for(var x:requests){var c=candidate(id,requiredLong(x,"candidateId"));if(!unique.add(c.id))throw ApiException.invalid("/sources","DUPLICATE","同じ候補を重複選択できません。");candidateVersion(c,x);all.add(c);}var d=obj(b.get("mergedCandidateData"));validateDraft(d);var refs=explicitBindings(id,d,list(b.get("resolutionBindings")));Set<Long> missing=new LinkedHashSet<>();all.forEach(c->missing.addAll(refIds(object(c.resolutionRefs))));missing.removeAll(refIds(refs));Object discard=b.get("discardResolutionIds");if(discard instanceof List<?> ids)for(Object rid:ids){resolution(id,Json.id(rid),null);missing.remove(Json.id(rid));}Boolean target;if(b.containsKey("resultRegistrationTarget")){if(!(b.get("resultRegistrationTarget") instanceof Boolean))throw ApiException.invalid("/resultRegistrationTarget","INVALID_TYPE","登録対象を選択してください。");target=(Boolean)b.get("resultRegistrationTarget");}else target=all.stream().map(c->c.registrationTarget).distinct().count()==1?all.getFirst().registrationTarget:null;var conflicts=new ArrayList<Object>();if(refs.get("scenarioResolutionId")==null&&all.stream().map(c->object(c.resolutionRefs).get("scenarioResolutionId")).filter(Objects::nonNull).filter(rid->!(discard instanceof List<?> discarded)||discarded.stream().noneMatch(did->Objects.equals(Json.id(did),Json.id(rid)))).distinct().count()>1)conflicts.add(map("slot",map("type","SCENARIO"),"message","採用する照合判断を選択してください。"));response.put("sourceVersions",all.stream().map(c->map("candidateId",c.id,"version",c.version)).toList());response.put("mergedCandidate",map("candidateData",d,"resolutionRefs",refs,"resolutions",bundle(id,refs),"confirmationStatus","UNCHECKED","registrationTarget",target));response.put("resolutionConflicts",conflicts);response.put("unmappedSourceResolutionRefs",missing);response.put("registrationTargetConflict",target==null);response.put("canApply",missing.isEmpty()&&conflicts.isEmpty()&&target!=null);}
  else throw new IllegalArgumentException();var p=new ImportPreview();p.importSessionId=id;p.revision=text(response.get("previewRevision"));p.operationKind=kind+(cid==null?"":"-"+cid);p.sessionVersion=session.version;p.payload=write(payload(b));var storedResponse=new LinkedHashMap<>(response);storedResponse.put("_snapshot",snapshot(id));p.response=write(storedResponse);s.save(p);return response;
 }
 public Object apply(long id,String kind,Long cid,Map<String,Object>b){owned(id);var session=s.lock(ImportSession.class,id);String revision=text(b.get("previewRevision"));var found=s.query(ImportPreview.class,"where e.revision=:revision","revision",revision==null?"":revision);if(found.isEmpty())throw new ApiException(409,"IMPORT_PREVIEW_STALE","もう一度プレビューしてください。");var p=found.getFirst();if(!p.importSessionId.equals(id))throw ApiException.notFound();if(!p.operationKind.equals(kind+(cid==null?"":"-"+cid))||p.sessionVersion!=session.version||!object(p.payload).equals(payload(b)))throw new ApiException(409,"IMPORT_PREVIEW_STALE","確認後に内容が更新されています。もう一度プレビューしてください。");var response=object(p.response);if(!write(response.get("_snapshot")).equals(write(snapshot(id))))throw new ApiException(409,"IMPORT_PREVIEW_STALE","確認後に内容が更新されています。もう一度プレビューしてください。");if(!session.status.equals("ACTIVE"))throw new ApiException(409,"IMPORT_PREVIEW_STALE","このインポートは完了しています。");
  if(kind.equals("BULK")){var operation=obj(b.get("operation"));String type=text(operation.get("type"));Long rid=null;var slot=obj(operation.get("slot"));if(type.equals("APPLY_RESOLUTION"))rid=changeResolution(id,operation,text(slot.get("type")));for(var target:list(b.get("targets"))){var c=candidate(id,requiredLong(target,"candidateId"));candidateVersion(c,target);var changes=new LinkedHashMap<String,Object>();switch(type){case "EXCLUDE"->changes.put("registrationTarget",false);case "INCLUDE"->changes.put("registrationTarget",true);case "APPLY_RESOLUTION","CLEAR_RESOLUTION"->{var targetSlot=new LinkedHashMap<>(slot);if(target.containsKey("candidateParticipationKey"))targetSlot.put("candidateParticipationKey",target.get("candidateParticipationKey"));var refs=object(c.resolutionRefs);bind(refs,object(c.candidateData),targetSlot,type.equals("CLEAR_RESOLUTION")?null:rid);c.resolutionRefs=write(refs);}default->throw ApiException.invalid("/operation/type","INVALID_OPERATION","一括操作を確認してください。");}patchCandidate(c,changes);}}
  else if(kind.equals("SPLIT")){var c=candidate(id,cid);editable(c);var parts=list(response.get("resultingCandidates"));if(parts.stream().anyMatch(x->!Boolean.TRUE.equals(x.get("canApply"))))throw new ApiException(409,"IMPORT_CONFLICT","照合判断の引継ぎ先を指定してください。");var traces=s.query(ImportCandidateSourceTrace.class,"where e.importCandidateId=:id","id",cid);for(var part:parts){var next=newCandidate(id,obj(part.get("candidateData")),obj(part.get("resolutionRefs")),c.registrationTarget);copyTraces(traces,next.id);}traces.forEach(s::remove);s.remove(c);}
  else{if(!Boolean.TRUE.equals(response.get("canApply")))throw new ApiException(409,"IMPORT_CONFLICT","統合前に確認事項を解決してください。");var merged=obj(response.get("mergedCandidate"));var next=newCandidate(id,obj(merged.get("candidateData")),obj(merged.get("resolutionRefs")),(Boolean)merged.get("registrationTarget"));for(var src:list(b.get("sources"))){var c=candidate(id,requiredLong(src,"candidateId"));editable(c);var traces=s.query(ImportCandidateSourceTrace.class,"where e.importCandidateId=:id","id",c.id);copyTraces(traces,next.id);traces.forEach(s::remove);s.remove(c);}}
  s.remove(p);tick(session);return map("sessionVersion",session.version);
 }
 private ImportCandidate newCandidate(long id,Map<String,Object>d,Map<String,Object>refs,boolean target){var c=new ImportCandidate();c.importSessionId=id;c.candidateData=write(d);c.resolutionRefs=write(refs);c.status=classify(d,refs);c.confirmationStatus="UNCHECKED";c.registrationTarget=target;c.registrationStatus=target?"PENDING":"EXCLUDED";s.save(c);s.flush();return c;}
 private void copyTraces(List<ImportCandidateSourceTrace> traces,long id){for(var old:traces){var t=new ImportCandidateSourceTrace();t.importCandidateId=id;t.importSourceId=old.importSourceId;t.sourceLocation=old.sourceLocation;s.save(t);}}
 private long formalResolution(long id,Long rid,String type,Long personId){if(rid==null)throw ApiException.invalid("/resolutionRefs","REQUIRED","照合判断を設定してください。");var r=resolution(id,rid,type);if(r.decision.equals("REUSE_EXISTING")){existing(type,r.existingEntityId);return r.existingEntityId;}if(r.createdEntityId!=null){existing(type,r.createdEntityId);return r.createdEntityId;}var draft=object(r.draftData);Map<String,Object> created=switch(type){case "SCENARIO"->obj(library.saveScenario(null,map("name",draft.get("name"),"gameSystem",draft.get("gameSystem"))));case "PERSON"->obj(library.savePerson(null,draft));case "PC"->obj(library.savePc(null,map("name",draft.get("name"),"personId",personId,"systemSettings",List.of())));default->throw new IllegalArgumentException();};r.createdEntityId=Json.id(created.get("id"));r.updatedAt=Instant.now();s.flush();return r.createdEntityId;}
 public Object register(long id,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));var requested=list(b.get("candidates"));if(requested.isEmpty())throw ApiException.invalid("/candidates","REQUIRED","登録対象を選択してください。");Set<Long> unique=new HashSet<>();for(var x:requested){var c=candidate(id,requiredLong(x,"candidateId"));if(!unique.add(c.id))throw ApiException.invalid("/candidates","DUPLICATE","候補が重複しています。");candidateVersion(c,x);}var results=new ArrayList<Object>();
  for(var x:requested){long cid=requiredLong(x,"candidateId"),expected=requiredLong(x,"expectedVersion");var connection=s.entityManager().unwrap(org.hibernate.Session.class);java.sql.Savepoint savepoint=connection.doReturningWork(java.sql.Connection::setSavepoint);try{var c=candidate(id,cid);if(!c.registrationTarget||!c.confirmationStatus.equals("CHECKED"))throw ApiException.invalid("/candidates","CONFIRMATION_REQUIRED","登録対象と確認済み状態を確認してください。");var d=object(c.candidateData);applyAssignments(d);validateDraft(d);if(list(d.get("unassignedValues")).stream().anyMatch(v->"UNASSIGNED".equals(obj(v.get("assignment")).get("type"))))throw ApiException.invalid("/candidateData/unassignedValues","UNASSIGNED","未割当の値を確認してください。");var refs=object(c.resolutionRefs);long scenario=formalResolution(id,Json.id(refs.get("scenarioResolutionId")),"SCENARIO",null);var parts=new ArrayList<Object>();for(var part:list(d.get("participations"))){var ref=list(refs.get("participations")).stream().filter(v->Objects.equals(v.get("candidateParticipationKey"),part.get("candidateParticipationKey"))).findFirst().orElseThrow(()->ApiException.invalid("/resolutionRefs","REQUIRED","人物の照合判断を設定してください。"));long person=formalResolution(id,Json.id(ref.get("personResolutionId")),"PERSON",null);Long pc=optional(part.get("pcName"))==null?null:formalResolution(id,Json.id(ref.get("pcResolutionId")),"PC",person);parts.add(map("personId",person,"pcId",pc,"role",part.get("role"),"ho",part.get("handout")));}var table=tables.save(null,scenario,map("tableName",d.get("tableName"),"tableDates",d.get("tableDates"),"recordingUrl",d.get("recordingUrl"),"participations",parts));c.registrationStatus="REGISTERED";c.registrationResult=write(map("registeredTableId",table.get("id")));c.updatedAt=Instant.now();s.flush();results.add(map("candidateId",cid,"requestedVersion",expected,"outcome","REGISTERED","candidateVersion",c.version,"registrationStatus","REGISTERED","registeredTableId",table.get("id"),"error",null));connection.doWork(q->q.releaseSavepoint(savepoint));}
   catch(ApiException error){connection.doWork(q->q.rollback(savepoint));s.entityManager().clear();var c=candidate(id,cid);c.registrationStatus="FAILED";c.registrationResult=write(map("error",map("code",error.code,"message",error.getMessage(),"fieldErrors",error.fields)));c.updatedAt=Instant.now();s.flush();results.add(map("candidateId",cid,"requestedVersion",expected,"outcome","FAILED","candidateVersion",c.version,"registrationStatus","FAILED","registeredTableId",null,"error",map("code",error.code,"message",error.getMessage(),"fieldErrors",error.fields)));}}
  session=s.find(ImportSession.class,id);tick(session);return map("sessionId",id,"sessionVersion",session.version,"results",results);
 }
 public Object complete(long id,Map<String,Object>b){var session=locked(id,requiredLong(b,"expectedSessionVersion"));if(candidates(id).stream().anyMatch(c->!Set.of("REGISTERED","EXCLUDED").contains(c.registrationStatus)))throw new ApiException(409,"IMPORT_CONFLICT","未処理の候補があります。");session.status="COMPLETED";session.completedAt=Instant.now();session.deleteAfterAt=session.completedAt.plus(Duration.ofHours(48));tick(session);return map("sessionVersion",session.version,"registeredTableCount",candidates(id).stream().filter(c->c.registrationStatus.equals("REGISTERED")).count());}
 @org.springframework.scheduling.annotation.Scheduled(fixedDelay=3600000) public void expire(){var now=Instant.now();for(var x:s.query(ImportSession.class,"where (e.status='ACTIVE' and e.expiresAt<:now) or (e.status='COMPLETED' and e.deleteAfterAt<:now)","now",now)){s.lock(ImportSession.class,x.id);for(var src:sources(x.id))cleanup.schedule(src.temporaryStorageKey);invalidate(x.id);sources(x.id).forEach(s::remove);s.remove(x);}}
}
