package jp.takukairo.importsession;
import org.springframework.stereotype.Component;
import jp.takukairo.common.*;
import static jp.takukairo.common.Json.*;
import java.util.*;
import java.io.*;
import java.nio.charset.*;
import java.time.*;
import org.apache.commons.csv.*;
import org.jsoup.Jsoup;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.text.TextContentRenderer;
@Component
public class ImportParser {
 public record Parsed(Map<String,Object> data,int lineStart,int lineEnd,String excerpt){}
 public String decode(byte[] data){try{return StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).decode(java.nio.ByteBuffer.wrap(data)).toString().replaceFirst("^\\uFEFF","");}catch(Exception e){return Charset.forName("windows-31j").decode(java.nio.ByteBuffer.wrap(data)).toString();}}
 public List<Parsed> parse(String name,String raw){String extension=name==null?"":name.toLowerCase(Locale.ROOT);if(extension.endsWith(".pdf"))throw ApiException.invalid("/sources","UNSUPPORTED_FORMAT","PDFは対象外です。");if(extension.endsWith(".csv"))return csv(raw);String plain=raw;if(extension.endsWith(".html")||extension.endsWith(".htm")){var document=Jsoup.parse(raw);document.select("p,div,br,li,tr,h1,h2,h3,h4").forEach(e->e.appendText("\n"));plain=document.wholeText();}if(extension.endsWith(".md")||extension.endsWith(".markdown"))plain=TextContentRenderer.builder().build().render(Parser.builder().build().parse(raw));var result=new ArrayList<Parsed>();String[] lines=plain.split("\\R",-1);Map<String,Object> current=empty();int start=1;List<Map<String,Object>> unassigned=new ArrayList<>();for(int i=0;i<lines.length;i++){String line=lines[i].trim();if(line.isBlank()){if(!current.get("scenarioName").equals("")||!unassigned.isEmpty()){current.put("unassignedValues",unassigned);result.add(new Parsed(current,start,i+1,String.join("\n",Arrays.copyOfRange(lines,start-1,i+1))));current=empty();unassigned=new ArrayList<>();}start=i+2;continue;}String[] pair=line.split("[:：]",2);if(pair.length==2&&Set.of("シナリオ","シナリオ名","Scenario").contains(pair[0].trim()))current.put("scenarioName",pair[1].trim());else if(pair.length==2&&Set.of("ゲームシステム","System").contains(pair[0].trim()))current.put("gameSystemName",pair[1].trim());else if(pair.length==2&&Set.of("卓名","Table").contains(pair[0].trim()))current.put("tableName",pair[1].trim());else if(pair.length==2&&Set.of("日付","実施日","Date").contains(pair[0].trim())){try{list(current.get("tableDates")).add(map("playedOn",LocalDate.parse(pair[1].trim()).toString()));}catch(Exception e){unassigned.add(unassigned(line));}}else if(pair.length==2&&Set.of("KP","PL").contains(pair[0].trim())){list(current.get("participations")).add(map("candidateParticipationKey","p-"+UUID.randomUUID(),"personName",pair[1].trim(),"role",pair[0].trim(),"pcName",null,"handout",null));}else unassigned.add(unassigned(line));}if(!current.get("scenarioName").equals("")||!unassigned.isEmpty()){current.put("unassignedValues",unassigned);result.add(new Parsed(current,start,lines.length,String.join("\n",Arrays.copyOfRange(lines,Math.min(start-1,lines.length),lines.length))));}return result;}
 private Map<String,Object> empty(){return map("scenarioName","","gameSystemName",null,"tableName",null,"tableDates",new ArrayList<>(),"recordingUrl",null,"participations",new ArrayList<>(),"unassignedValues",new ArrayList<>());}
 private Map<String,Object> unassigned(String raw){return map("itemKey","u-"+UUID.randomUUID(),"rawValue",raw,"assignment",map("type","UNASSIGNED","candidateParticipationKey",null));}
 private List<Parsed> csv(String text){var result=new ArrayList<Parsed>();try(var parser=CSVFormat.DEFAULT.builder().setHeader().setSkipHeaderRecord(true).get().parse(new StringReader(text))){for(var row:parser){var data=empty();var unresolved=new ArrayList<Map<String,Object>>();for(var e:row.toMap().entrySet()){String k=e.getKey().trim(),v=e.getValue();if(v.isBlank())continue;switch(k){case "シナリオ","シナリオ名","scenarioName"->data.put("scenarioName",v);case "ゲームシステム","gameSystemName"->data.put("gameSystemName",v);case "卓名","tableName"->data.put("tableName",v);case "日付","playedOn"->{try{list(data.get("tableDates")).add(map("playedOn",LocalDate.parse(v).toString()));}catch(Exception x){unresolved.add(unassigned(v));}}case "KP","PL"->list(data.get("participations")).add(map("candidateParticipationKey","p-"+UUID.randomUUID(),"personName",v,"role",k,"pcName",null,"handout",null));default->unresolved.add(unassigned(k+": "+v));}}data.put("unassignedValues",unresolved);result.add(new Parsed(data,(int)row.getRecordNumber()+1,(int)row.getRecordNumber()+1,row.toString()));}}catch(Exception e){throw ApiException.invalid("/sources","INVALID_CSV","CSVの内容を確認してください。");}return result;}
}
