package jp.takukairo.table;
import jp.takukairo.common.*;
import jp.takukairo.model.*;
import jp.takukairo.security.*;
import jp.takukairo.gamesystem.*;
import jp.takukairo.scenario.*;
import static jp.takukairo.common.Json.*;
import static jp.takukairo.common.Validation.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;
@Service @Transactional
public class TableService {
 private final Store s;private final CurrentUser user;private final LibraryService library;private final Profiles profiles;
 public TableService(Store s,CurrentUser u,LibraryService l,Profiles p){this.s=s;user=u;library=l;profiles=p;}
 public Map<String,Object> dto(TrpgTable t){var dates=s.query(TableDate.class,"where e.tableId=:id order by e.playedOn,e.id","id",t.id);var parts=s.query(Participation.class,"where e.tableId=:id order by e.role,e.displayOrder","id",t.id);var unnamed=s.query(TrpgTable.class,"where e.scenarioId=:id and e.tableName is null order by e.createdAt,e.id","id",t.scenarioId);int number=0;for(int i=0;i<unnamed.size();i++)if(unnamed.get(i).id.equals(t.id))number=i+1;return map("id",t.id,"version",t.version,"scenarioId",t.scenarioId,"scenario",library.scenarioDto(s.find(Scenario.class,t.scenarioId)),"tableName",t.tableName,"recordingUrl",t.recordingUrl,"createdAt",t.createdAt,"tableDates",dates.stream().map(d->map("id",d.id,"playedOn",d.playedOn,"version",d.version)).toList(),"participations",parts.stream().map(this::participationDto).toList());}
 private Object participationDto(Participation p){var state=s.query(EndPcState.class,"where e.participationId=:id","id",p.id);return map("id",p.id,"version",p.version,"personId",p.personId,"person",library.personDto(s.find(Person.class,p.personId)),"pcId",p.pcId,"pc",p.pcId==null?null:library.pcDto(s.find(Pc.class,p.pcId)),"role",p.role,"displayOrder",p.displayOrder,"ho",p.ho,"displayQuote",p.displayQuote,"spotlightType",p.spotlightType,"endPcState",state.isEmpty()?null:stateDto(state.getFirst()));}
 private Object stateDto(EndPcState e){return map("id",e.id,"version",e.version,"profileKey",e.profileKey,"statusValues",object(e.statusValues),"growth",e.growth,"outcome",e.outcome,"aftereffects",e.aftereffects);}
 public Object get(long id){return dto(user.owned(TrpgTable.class,id));}
 public Object forScenario(long id){user.owned(Scenario.class,id);return s.query(TrpgTable.class,"where e.scenarioId=:id order by e.createdAt,e.id","id",id).stream().map(this::dto).toList();}
 public Object appearances(long id){user.owned(Pc.class,id);return s.query(Participation.class,"where e.pcId=:id","id",id).stream().sorted(Comparator.comparing((Participation p)->library.basis(s.find(TrpgTable.class,p.tableId)),Comparator.reverseOrder())).map(p->{var t=s.find(TrpgTable.class,p.tableId);return map("table",dto(t),"participationId",p.id,"person",library.personDto(s.find(Person.class,p.personId)));}).toList();}
 public Map<String,Object> save(Long id,long scenarioId,Map<String,Object>b){var scenario=user.owned(Scenario.class,scenarioId);var t=id==null?new TrpgTable():user.owned(TrpgTable.class,id);if(id!=null){t=s.lock(TrpgTable.class,id);Store.version(t.version,requiredLong(b,"version"));}else{t.userId=user.id();t.scenarioId=scenarioId;s.save(t);s.flush();}t.scenarioId=scenarioId;t.tableName=optional(b.get("tableName"));if(t.tableName!=null&&t.tableName.codePointCount(0,t.tableName.length())>255)throw ApiException.invalid("/tableName","TOO_LONG","255文字以下にしてください。");t.recordingUrl=url(b.get("recordingUrl"),"/recordingUrl");
  var oldDates=s.query(TableDate.class,"where e.tableId=:id","id",t.id);Set<Long> keptDates=new HashSet<>();int i=0;for(var x:list(b.get("tableDates"))){Long child=Json.id(x.get("id"));var d=child==null?new TableDate():s.find(TableDate.class,child);if(child!=null&&!d.tableId.equals(t.id))throw ApiException.notFound();try{d.playedOn=LocalDate.parse(text(x.get("playedOn")));}catch(Exception e){throw ApiException.invalid("/tableDates/"+i+"/playedOn","INVALID_DATE","日付を入力してください。");}d.tableId=t.id;d.updatedAt=Instant.now();if(child==null)s.save(d);else keptDates.add(child);i++;}oldDates.stream().filter(x->!keptDates.contains(x.id)).forEach(s::remove);
  var oldParts=s.query(Participation.class,"where e.tableId=:id","id",t.id);Set<Long> kept=new HashSet<>();int kp=0,pl=0;i=0;for(var x:list(b.get("participations"))){String path="/participations/"+i;Long child=Json.id(x.get("id"));var p=child==null?new Participation():s.find(Participation.class,child);if(child!=null&&!p.tableId.equals(t.id))throw ApiException.notFound();long person=requiredLong(x,"personId");user.owned(Person.class,person);Long pc=Json.id(x.get("pcId"));if(pc!=null)user.owned(Pc.class,pc);String role=text(x.get("role"));if(!Set.of("KP","PL").contains(role==null?"":role))throw ApiException.invalid(path+"/role","INVALID_ROLE","役割を選択してください。");if(role.equals("KP")&&(pc!=null||optional(x.get("ho"))!=null||optional(x.get("displayQuote"))!=null||!obj(x.get("endPcState")).isEmpty()))throw ApiException.invalid(path+"/role","INVALID_ROLE","KP / SKPではPC・HO・飾り台詞・終了時データを解除してください。");String quote=optional(x.get("displayQuote"));if(graphemes(quote)>24)throw ApiException.invalid(path+"/displayQuote","TOO_LONG","24文字以下にしてください。");var prior=s.query(EndPcState.class,"where e.participationId=:id","id",p.id==null?-1L:p.id);EndPcState state=prior.isEmpty()?null:prior.getFirst();boolean changed=!Objects.equals(p.pcId,pc);
   Map<String,Object> requested=obj(x.get("endPcState"));Long stateId=Json.id(requested.get("id"));if(stateId!=null&&(state==null||!state.id.equals(stateId)))throw ApiException.notFound();if(changed&&state!=null){s.remove(state);s.flush();state=null;}if(pc==null&&state!=null){s.remove(state);state=null;}p.tableId=t.id;p.personId=person;p.pcId=pc;p.role=role;p.displayOrder=role.equals("KP")?++kp:++pl;p.ho=optional(x.get("ho"));p.displayQuote=quote;p.spotlightType=p.ho==null?(quote==null?null:"QUOTE"):(quote==null?"HO":Set.of("HO","QUOTE").contains(text(x.get("spotlightType")))?text(x.get("spotlightType")):"HO");p.updatedAt=Instant.now();if(child==null){s.save(p);s.flush();}else kept.add(child);
   boolean empty=requested.isEmpty()||obj(requested.get("statusValues")).values().stream().allMatch(Objects::isNull)&&optional(requested.get("growth"))==null&&optional(requested.get("outcome"))==null&&optional(requested.get("aftereffects"))==null;
   if(pc==null||empty){if(state!=null)s.remove(state);}else{String key=state==null?Optional.ofNullable(profiles.resolveProfile(scenario.gameSystem)).map(z->text(z.get("profileKey"))).orElse(null):state.profileKey;if(state==null&&requested.get("profileKey")!=null&&!Objects.equals(key,requested.get("profileKey")))throw ApiException.invalid(path+"/endPcState/profileKey","PROFILE_MISMATCH","シナリオの設定形式と一致しません。");profiles.validateState(key,obj(requested.get("statusValues")),path+"/endPcState/statusValues");String outcome=optional(requested.get("outcome"));if(outcome!=null&&!Set.of("SURVIVED","LOST").contains(outcome))throw ApiException.invalid(path+"/endPcState/outcome","INVALID_OPTION","結末を確認してください。");if(state==null){state=new EndPcState();state.participationId=p.id;state.profileKey=key;s.save(state);}state.statusValues=write(obj(requested.get("statusValues")));state.growth=longText(requested.get("growth"),path+"/endPcState/growth",500);state.aftereffects=longText(requested.get("aftereffects"),path+"/endPcState/aftereffects",500);state.outcome=outcome;state.updatedAt=Instant.now();}i++;
  }for(var p:oldParts)if(!kept.contains(p.id)){s.query(EndPcState.class,"where e.participationId=:id","id",p.id).forEach(s::remove);s.remove(p);}t.updatedAt=Instant.now();s.flush();return dto(t);
 }
 public void delete(long id){var t=user.owned(TrpgTable.class,id);s.query(Participation.class,"where e.tableId=:id","id",id).forEach(p->{s.query(EndPcState.class,"where e.participationId=:id","id",p.id).forEach(s::remove);s.remove(p);});s.query(TableDate.class,"where e.tableId=:id","id",id).forEach(s::remove);s.remove(t);}
 public Object previous(long pcId,Map<String,Object>b){user.owned(Pc.class,pcId);var sc=user.owned(Scenario.class,requiredLong(b,"scenarioId"));Long target=Json.id(b.get("targetTableId"));if(target!=null)user.owned(TrpgTable.class,target);var profile=profiles.resolveProfile(sc.gameSystem);if(profile==null)return map("candidate",null,"reason","UNSUPPORTED_TARGET_PROFILE");String key=text(profile.get("profileKey"));if(!(b.get("tableDates") instanceof List<?> dates))throw ApiException.invalid("/tableDates","REQUIRED","日付一覧が必要です。");var parsedDates=new ArrayList<LocalDate>();for(int i=0;i<dates.size();i++){try{if(!(dates.get(i) instanceof String))throw new IllegalArgumentException();parsedDates.add(LocalDate.parse((String)dates.get(i)));}catch(Exception invalid){throw ApiException.invalid("/tableDates/"+i,"INVALID_DATE","日付を確認してください。");}}LocalDate cutoff=parsedDates.stream().min(Comparator.naturalOrder()).orElse(null);
  record History(Participation part,TrpgTable table,EndPcState state,LocalDate date){}var all=new ArrayList<History>();boolean history=false,matched=false;for(var p:s.query(Participation.class,"where e.pcId=:id","id",pcId)){if(Objects.equals(p.tableId,target))continue;var state=s.query(EndPcState.class,"where e.participationId=:id","id",p.id);if(state.isEmpty())continue;history=true;if(!Objects.equals(state.getFirst().profileKey,key))continue;matched=true;var t=s.find(TrpgTable.class,p.tableId);LocalDate date=s.query(TableDate.class,"where e.tableId=:id order by e.playedOn desc","id",t.id).stream().findFirst().map(d->d.playedOn).orElse(null);if(cutoff!=null&&(date==null||!date.isBefore(cutoff)))continue;all.add(new History(p,t,state.getFirst(),date));}
  if(all.isEmpty())return map("candidate",null,"reason",!history?"NO_HISTORY":!matched?"NO_PROFILE_MATCH":"NO_PREVIOUS_BEFORE_TARGET");all.sort(Comparator.comparing(History::date,Comparator.nullsLast(Comparator.reverseOrder())).thenComparing(h->h.table.createdAt,Comparator.reverseOrder()).thenComparing(h->h.table.id,Comparator.reverseOrder()).thenComparing(h->h.part.id,Comparator.reverseOrder()));var h=all.getFirst();boolean tied=all.size()>1&&Objects.equals(all.get(1).date,h.date);Object basis=h.date==null?map("type","CREATED_AT_FALLBACK","registeredAt",h.table.createdAt,"confidence","LOW"):map("type","TABLE_DATE","playedOn",h.date,"confidence",cutoff==null||tied?"LOW":"HIGH");return map("candidate",map("sourceTableId",h.table.id,"sourceParticipationId",h.part.id,"profileKey",key,"statusValues",object(h.state.statusValues),"basis",basis),"reason",null);
 }
 public Map<String,Object> activity(List<TrpgTable> tables){Long self=user.user().selfPersonId;Set<Long> scenarios=new HashSet<>(),ids=new HashSet<>(),pl=new HashSet<>(),kp=new HashSet<>();for(var t:tables)for(var p:s.query(Participation.class,"where e.tableId=:id and e.personId=:self","id",t.id,"self",self)){scenarios.add(t.scenarioId);ids.add(t.id);(p.role.equals("PL")?pl:kp).add(t.id);}return map("scenarioCount",scenarios.size(),"tableCount",ids.size(),"plParticipationCount",pl.size(),"kpParticipationCount",kp.size());}
 public Object summary(){return activity(s.query(TrpgTable.class,"where e.userId=:u","u",user.id()));}
 public Object byMonth(int year){var tables=s.query(TrpgTable.class,"where e.userId=:u","u",user.id());var out=new ArrayList<Object>();for(int m=1;m<=12;m++){final int month=m;out.add(map("year",year,"month",m,"summary",activity(tables.stream().filter(t->{var date=library.basis(t).atZone(ZoneOffset.UTC);return date.getYear()==year&&date.getMonthValue()==month;}).toList())));}return out;}
 public Object byYear(){var tables=s.query(TrpgTable.class,"where e.userId=:u","u",user.id());return tables.stream().map(t->library.basis(t).atZone(ZoneOffset.UTC).getYear()).distinct().sorted(Comparator.reverseOrder()).map(y->map("year",y,"summary",activity(tables.stream().filter(t->library.basis(t).atZone(ZoneOffset.UTC).getYear()==y).toList()))).toList();}
}
