import {createContext,useContext,useState,useEffect,useRef,type ReactNode} from 'react';
import {Link,NavLink,Outlet,useLocation,useNavigate,Navigate} from 'react-router-dom';
import {get,mutate,freshCsrf,clearCsrf,ApiError} from './api/client';
import type {Session} from './api/types';
import {Dialog,ConfirmContext,useErrors,ErrorPanel,Field,fieldProps,canLogout} from './components/common';
export const SessionContext=createContext<{session:Session|null;sessionError:ApiError|null;retrySession:()=>Promise<void>;refresh:()=>Promise<void>;toast:(text:string)=>void}>({session:null,sessionError:null,retrySession:async()=>{},refresh:async()=>{},toast:()=>{}});
export function useSession(){return useContext(SessionContext)}
export function Root(){const [session,setSession]=useState<Session|null>(null),[sessionError,setSessionError]=useState<ApiError|null>(null),[toast,setToast]=useState(''),[expired,setExpired]=useState(false),[offline,setOffline]=useState(!navigator.onLine);const confirm=useContext(ConfirmContext);const navigate=useNavigate();function connectionError(e:unknown){return e instanceof ApiError?e:new ApiError(0,{code:'TRANSPORT_ERROR',message:'接続を確認できません。',fieldErrors:[]})}async function refresh(){try{setSession(await get<Session>('/session'));setSessionError(null)}catch(e){setSessionError(connectionError(e));throw e}}async function retrySession(){setSessionError(null);try{await freshCsrf();await refresh()}catch(e){setSessionError(connectionError(e))}}useEffect(()=>{void retrySession();const onExpired=()=>setExpired(true),online=()=>setOffline(!navigator.onLine);window.addEventListener('session-expired',onExpired);window.addEventListener('online',online);window.addEventListener('offline',online);return()=>{window.removeEventListener('session-expired',onExpired);window.removeEventListener('online',online);window.removeEventListener('offline',online)}},[]);useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer)}},[toast]);async function login(){await mutate('/dev/session','POST');clearCsrf();await freshCsrf();await refresh();setExpired(false)}return <SessionContext.Provider value={{session,sessionError,retrySession,refresh,toast:setToast}}>{offline&&<div className="offline" role="status">オフラインです。現在は変更内容を保存できません。接続後にもう一度保存してください。</div>}<Outlet/>{toast&&<div className="toast" role="status" aria-atomic="true">{toast}</div>}{expired&&<Dialog title="セッションの有効期限が切れました" onClose={()=>setExpired(false)}><p>入力を保持しています。再ログイン後、保存をもう一度実行してください。</p>{import.meta.env.DEV&&<button className="primary" onClick={()=>void login()}>テストユーザーで再ログイン</button>}</Dialog>}</SessionContext.Provider>}
export function Protected({children}:{children:ReactNode}){const {session,sessionError,retrySession}=useSession();if(!session)return sessionError?<main className="page form-page"><h1>接続を確認できません</h1><ErrorPanel error={sessionError}/><button onClick={()=>void retrySession()}>接続を再確認</button></main>:<div className="page" role="status">接続を確認しています…</div>;if(!session.authenticated)return <Navigate to={import.meta.env.DEV?'/dev-login':'/login'} replace/>;if(!session.user?.selfPerson)return <Navigate to="/setup/self-person" replace/>;return <>{children}</>}
export function Shell(){const {session,refresh}=useSession();const nav=useNavigate();const [account,setAccount]=useState(false);return <><header className="app-header"><Link className="brand" to="/">卓回廊</Link><nav aria-label="主な画面"><NavLink to="/" end>HOME</NavLink><NavLink to="/pcs">PL / PC</NavLink><NavLink to="/import">IMPORT</NavLink></nav><button className="account-entrance quiet" onClick={()=>setAccount(true)}>{session?.user?.selfPerson?.displayName??'アカウント'}</button></header><Outlet/><footer className="app-footer"><Link to="/terms">利用規約</Link><Link to="/privacy">プライバシーポリシー</Link><span>LOCAL TEST</span></footer>{account&&<Dialog title="アカウント" onClose={()=>setAccount(false)}><p>{session?.user?.selfPerson?.displayName}</p><p><Link to="/account" onClick={()=>setAccount(false)}>アカウント設定</Link></p><button onClick={()=>{setAccount(false);void canLogout().then(async ok=>{if(!ok)return;await mutate('/logout','POST');clearCsrf();await freshCsrf();await refresh();nav('/dev-login')})}}>ログアウト</button></Dialog>}</>}
export function Login({dev=false}:{dev?:boolean}){const {refresh}=useSession();const navigate=useNavigate();const {error,report}=useErrors();const [busy,setBusy]=useState(false);async function login(){setBusy(true);try{await freshCsrf();await mutate('/dev/session','POST');clearCsrf();await freshCsrf();await refresh();navigate('/')}catch(e){report(e)}finally{setBusy(false)}}return <main className="page form-page"><p className="kicker">LOCAL TEST</p><h1>卓回廊</h1><p>TRPGの作品と、卓の記憶を並べる個人の回廊。</p><ErrorPanel error={error}/>{dev?<button className="primary" disabled={busy} onClick={()=>void login()}>固定テストユーザーでログイン</button>:<><p>Production Google認証は今回の対象外です。</p>{import.meta.env.DEV&&<Link to="/dev-login">ローカルテスト用ログインへ</Link>}</>}</main>}
export function Setup(){const {refresh}=useSession(),navigate=useNavigate();const [name,setName]=useState('');const {error,report}=useErrors();return <main className="page form-page"><h1>TRPGで使う名前</h1><p>このテスト環境内で使う名前を設定します。</p><ErrorPanel error={error}/><form onSubmit={e=>{e.preventDefault();void mutate('/self-person','POST',{displayName:name}).then(async()=>{await refresh();navigate('/')}).catch(report)}}><Field label="表示名" path="/displayName" error={error}><input {...fieldProps('/displayName',error)} required value={name} onChange={e=>setName(e.target.value)}/></Field><button className="primary">設定して始める</button></form></main>}
export function Legal({privacy=false}:{privacy?:boolean}){return <main className="page form-page"><h1>{privacy?'プライバシーポリシー':'利用規約'}</h1><p>TEST IMPLEMENTATION / FINAL LEGAL TEXT NOT YET FIXED</p><p>ローカルテスト用の仮ページです。正式本文はProduction Deferredです。</p><Link to="/">ホームへ</Link></main>}
export function NotFound(){return <main className="page"><h1>対象が見つかりません</h1><Link to="/">ホームへ</Link></main>}
export function useResource<T>(path:string|null){const previousPath=useRef(path);const [data,setData]=useState<T|null>(null),[error,setError]=useState<unknown>(null),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);useEffect(()=>{if(!path){setLoading(false);return}if(previousPath.current!==path){setData(null);previousPath.current=path}const controller=new AbortController();setLoading(true);setError(null);void get<T>(path,controller.signal).then(value=>{setData(value);setError(null)}).catch(e=>{if(!controller.signal.aborted)setError(e)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[path,revision]);return {data,setData,error,loading,reload:()=>setRevision(v=>v+1)}}
