package jp.takukairo.image;
import org.springframework.stereotype.Component;
import jp.takukairo.common.*;
import javax.imageio.*;
import java.awt.image.BufferedImage;
import java.awt.*;
import java.io.*;
import com.drew.imaging.ImageMetadataReader;
import com.drew.metadata.exif.ExifIFD0Directory;
@Component
public class LocalImageProcessor implements ImageProcessor {
 public Processed process(byte[] bytes){if(bytes.length>10*1024*1024)throw reject("画像は10MB以下にしてください。");String format=magic(bytes);if(format==null)throw reject("JPEG・PNG・静止WebPを選択してください。");if(format.equals("webp")){for(int i=12;i+8<bytes.length;){String chunk=new String(bytes,i,4,java.nio.charset.StandardCharsets.US_ASCII);if(chunk.equals("ANIM")||chunk.equals("ANMF")||chunk.equals("VP8X")&&(bytes[i+8]&2)!=0)throw reject("アニメーション画像は利用できません。");long len=Integer.toUnsignedLong(java.nio.ByteBuffer.wrap(bytes,i+4,4).order(java.nio.ByteOrder.LITTLE_ENDIAN).getInt());if(len>bytes.length)break;i+=(int)(8+len+(len%2));}}
  try(var input=ImageIO.createImageInputStream(new ByteArrayInputStream(bytes))){var readers=ImageIO.getImageReaders(input);if(!readers.hasNext())throw reject("画像を解析できません。");var reader=readers.next();try{reader.setInput(input,true,true);int width=reader.getWidth(0),height=reader.getHeight(0);dimensions(width,height);BufferedImage image=reader.read(0);int orientation=1;try{var metadata=ImageMetadataReader.readMetadata(new ByteArrayInputStream(bytes));var exif=metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);if(exif!=null&&exif.containsTag(ExifIFD0Directory.TAG_ORIENTATION))orientation=exif.getInt(ExifIFD0Directory.TAG_ORIENTATION);}catch(Exception ignored){}image=orient(image,orientation);dimensions(image.getWidth(),image.getHeight());var master=new ByteArrayOutputStream();ImageIO.write(image,"png",master);double ratio=Math.min(1,2048.0/Math.max(image.getWidth(),image.getHeight()));BufferedImage derivative=new BufferedImage(Math.max(1,(int)Math.round(image.getWidth()*ratio)),Math.max(1,(int)Math.round(image.getHeight()*ratio)),BufferedImage.TYPE_INT_ARGB);var g=derivative.createGraphics();g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BICUBIC);g.drawImage(image,0,0,derivative.getWidth(),derivative.getHeight(),null);g.dispose();var webp=new ByteArrayOutputStream();var writers=ImageIO.getImageWritersByFormatName("webp");if(!writers.hasNext())throw new IllegalStateException("WebP encoder missing");var writer=writers.next();try(var output=ImageIO.createImageOutputStream(webp)){writer.setOutput(output);var param=writer.getDefaultWriteParam();if(param.canWriteCompressed()){param.setCompressionMode(javax.imageio.ImageWriteParam.MODE_EXPLICIT);var types=param.getCompressionTypes();if(types!=null)for(String type:types)if(type.toLowerCase().contains("lossy")){param.setCompressionType(type);break;}param.setCompressionQuality(.85f);}writer.write(null,new IIOImage(derivative,null,null),param);}finally{writer.dispose();}return new Processed(master.toByteArray(),webp.toByteArray());}finally{reader.dispose();}}
  catch(ApiException e){throw e;}catch(Exception e){throw reject("画像を読み取れませんでした。");}
 }
 private BufferedImage orient(BufferedImage image,int o){if(o<=1||o>8)return image;int w=image.getWidth(),h=image.getHeight();boolean swap=o>=5;var out=new BufferedImage(swap?h:w,swap?w:h,BufferedImage.TYPE_INT_ARGB);for(int y=0;y<h;y++)for(int x=0;x<w;x++){int dx=x,dy=y;switch(o){case 2->{dx=w-1-x;}case 3->{dx=w-1-x;dy=h-1-y;}case 4->{dy=h-1-y;}case 5->{dx=y;dy=x;}case 6->{dx=h-1-y;dy=x;}case 7->{dx=h-1-y;dy=w-1-x;}case 8->{dx=y;dy=w-1-x;}}out.setRGB(dx,dy,image.getRGB(x,y));}return out;}
 private void dimensions(int w,int h){if(w<=0||h<=0||w>8192||h>8192||(long)w*h>32_000_000||(long)w*h*6>192L*1024*1024)throw reject("画像の縦横サイズを小さくしてください。");}
 private String magic(byte[] b){if(b.length>=8&&(b[0]&255)==137&&b[1]==80&&b[2]==78&&b[3]==71)return "png";if(b.length>=3&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255)return "jpeg";if(b.length>=12&&new String(b,0,4,java.nio.charset.StandardCharsets.US_ASCII).equals("RIFF")&&new String(b,8,4,java.nio.charset.StandardCharsets.US_ASCII).equals("WEBP"))return "webp";return null;}
 private ApiException reject(String message){return ApiException.invalid("/file","INVALID_IMAGE",message);}
}
